# $Id: Makefile.inc 2243 2009-12-23 06:45:17Z peter $

#TESTS += modules/preprocs/gas/tests/rawpp_test.sh

#EXTRA_DIST += modules/preprocs/gas/tests/rawpp_test.sh
#EXTRA_DIST += modules/preprocs/gas/tests/longline.asm
#EXTRA_DIST += modules/preprocs/gas/tests/longline.hex
