/* Generated by tuneup.c, 2009-02-05, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          28
#define MUL_TOOM3_THRESHOLD             153

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          32
#define SQR_TOOM3_THRESHOLD             218

#define MULLOW_BASECASE_THRESHOLD         5
#define MULLOW_DC_THRESHOLD              28
#define MULLOW_MUL_N_THRESHOLD          486

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 60
#define POWM_THRESHOLD                  142

#define GCD_ACCEL_THRESHOLD             115
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             13
#define GET_STR_PRECOMPUTE_THRESHOLD     18
#define SET_STR_THRESHOLD              7059

#define MUL_FFT_TABLE  { 784, 1696, 3648, 7936, 19456, 53248, 180224, 458752, 0 }
#define MUL_FFT_MODF_THRESHOLD          800
#define MUL_FFT_THRESHOLD             15872

#define SQR_FFT_TABLE  { 848, 1824, 3648, 7936, 15360, 45056, 147456, 458752, 0 }
#define SQR_FFT_MODF_THRESHOLD          864
#define SQR_FFT_THRESHOLD             13824

/* Tuneup completed successfully, took 73 seconds */
