
/* On a AMD Sempron 1800Mhz */

/* Generated by tuneup.c, 2008-12-24, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          26
#define MUL_TOOM3_THRESHOLD             180

#define SQR_BASECASE_THRESHOLD            0  /* always */
#define SQR_KARATSUBA_THRESHOLD          61
#define SQR_TOOM3_THRESHOLD             193

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              26
#define MULLOW_MUL_N_THRESHOLD          582

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 68
#define POWM_THRESHOLD                  154

#define GCD_ACCEL_THRESHOLD             113
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             14
#define GET_STR_PRECOMPUTE_THRESHOLD     22
#define SET_STR_THRESHOLD              8540

#define MUL_FFT_TABLE  { 752, 1632, 3648, 7424, 19456, 45056, 180224, 458752, 0 }
#define MUL_FFT_MODF_THRESHOLD          768
#define MUL_FFT_THRESHOLD             13824

#define SQR_FFT_TABLE  { 656, 1440, 3136, 5888, 15360, 36864, 114688, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          672
#define SQR_FFT_THRESHOLD              8704

/* Tuneup completed successfully, took 12 seconds */
