/* Generated by tuneup.c, 2009-10-07, gcc 4.3 */

#define MUL_KARATSUBA_THRESHOLD          18
#define MUL_TOOM3_THRESHOLD              73
#define MUL_TOOM4_THRESHOLD             202
#define MUL_TOOM7_THRESHOLD             270

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          30
#define SQR_TOOM3_THRESHOLD             192
#define SQR_TOOM4_THRESHOLD             199
#define SQR_TOOM7_THRESHOLD             208

#define MULLOW_BASECASE_THRESHOLD         6
#define MULLOW_DC_THRESHOLD             105
#define MULLOW_MUL_THRESHOLD           6203

#define MULHIGH_BASECASE_THRESHOLD        6
#define MULHIGH_DC_THRESHOLD            144
#define MULHIGH_MUL_THRESHOLD          6203

#define MULMOD_2EXPM1_THRESHOLD          18

#define DIV_SB_PREINV_THRESHOLD          48
#define DIV_DC_THRESHOLD                 55
#define POWM_THRESHOLD                  330
#define FAC_UI_THRESHOLD               2046

#define GCD_ACCEL_THRESHOLD               1
#define GCDEXT_THRESHOLD                 89
#define JACOBI_BASE_METHOD                1

#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* native */
#define DIVREM_2_THRESHOLD               15
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 9
#define MOD_1_2_THRESHOLD                37
#define MOD_1_3_THRESHOLD                63
#define DIVREM_HENSEL_QR_1_THRESHOLD     10
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      4
#define DIVREM_EUCLID_HENSEL_THRESHOLD      9

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             23
#define GET_STR_PRECOMPUTE_THRESHOLD     38
#define SET_STR_THRESHOLD              7059

#define MUL_FFT_FULL_THRESHOLD              7168

#define SQR_FFT_FULL_THRESHOLD              4352

/* Tuneup completed successfully, took 40 seconds */
