/* Generated by tuneup.c, 2010-03-24, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          24
#define MUL_TOOM3_THRESHOLD              67
#define MUL_TOOM4_THRESHOLD             351
#define MUL_TOOM8H_THRESHOLD            466

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          34
#define SQR_TOOM3_THRESHOLD             113
#define SQR_TOOM4_THRESHOLD             522
#define SQR_TOOM8_THRESHOLD             562

#define POWM_THRESHOLD                  349

#define GCD_ACCEL_THRESHOLD               2
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                31
#define DIVREM_HENSEL_QR_1_THRESHOLD      7
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      6
#define DIVREM_EUCLID_HENSEL_THRESHOLD     13

#define ROOTREM_THRESHOLD                 8

#define GET_STR_DC_THRESHOLD             13
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD            410
#define SET_STR_PRECOMPUTE_THRESHOLD   2359

#define MUL_FFT_TABLE  { 432, 928, 2240, 2816, 7168, 20480, 81920, 327680, 1835008, 5242880, 20971520, 83886080, 0 }
#define MUL_FFT_MODF_THRESHOLD          432
#define MUL_FFT_FULL_THRESHOLD         2368

#define SQR_FFT_TABLE  { 432, 928, 2240, 2816, 7168, 28672, 81920, 327680, 1310720, 5242880, 20971520, 83886080, 0 }
#define SQR_FFT_MODF_THRESHOLD          400
#define SQR_FFT_FULL_THRESHOLD         2368

#define MULLOW_BASECASE_THRESHOLD         9
#define MULLOW_DC_THRESHOLD              30
#define MULLOW_MUL_THRESHOLD           4266

#define MULHIGH_BASECASE_THRESHOLD       13
#define MULHIGH_DC_THRESHOLD             33
#define MULHIGH_MUL_THRESHOLD          4266

#define MULMOD_2EXPM1_THRESHOLD          16

#define FAC_UI_THRESHOLD              17010
#define DC_DIV_QR_THRESHOLD              60
#define DC_DIVAPPR_Q_N_THRESHOLD        146
#define INV_DIV_QR_THRESHOLD           3762
#define INV_DIVAPPR_Q_N_THRESHOLD       146
#define DC_DIV_Q_THRESHOLD              177
#define INV_DIV_Q_THRESHOLD            7071
#define DC_DIVAPPR_Q_THRESHOLD          162
#define INV_DIVAPPR_Q_THRESHOLD       15290
#define DC_BDIV_QR_THRESHOLD             58
#define DC_BDIV_Q_THRESHOLD              34
/* Tuneup completed successfully, took 1917 seconds */
