/* Generated by tuneup.c, 2014-03-19, gcc 4.7 */

#define MUL_KARATSUBA_THRESHOLD          20
#define MUL_TOOM3_THRESHOLD             129
#define MUL_TOOM4_THRESHOLD             226
#define MUL_TOOM8H_THRESHOLD            418

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          30
#define SQR_TOOM3_THRESHOLD             121
#define SQR_TOOM4_THRESHOLD             532
#define SQR_TOOM8_THRESHOLD             552

#define POWM_THRESHOLD                  349

#define HGCD_THRESHOLD                   75
#define GCD_DC_THRESHOLD                532
#define GCDEXT_DC_THRESHOLD             381
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                10
#define MOD_1_3_THRESHOLD                32
#define DIVREM_HENSEL_QR_1_THRESHOLD      7
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      6
#define DIVREM_EUCLID_HENSEL_THRESHOLD    159

#define ROOTREM_THRESHOLD                 8

#define GET_STR_DC_THRESHOLD             14
#define GET_STR_PRECOMPUTE_THRESHOLD     22
#define SET_STR_DC_THRESHOLD            537
#define SET_STR_PRECOMPUTE_THRESHOLD    899

#define MUL_FFT_FULL_THRESHOLD         7232

#define SQR_FFT_FULL_THRESHOLD         3904

#define MULLOW_BASECASE_THRESHOLD         9
#define MULLOW_DC_THRESHOLD              32
#define MULLOW_MUL_THRESHOLD           5732

#define MULHIGH_BASECASE_THRESHOLD       13
#define MULHIGH_DC_THRESHOLD             33
#define MULHIGH_MUL_THRESHOLD          5620

#define MULMOD_2EXPM1_THRESHOLD          18

#define FAC_UI_THRESHOLD               8171
#define SB_DIVAPPR_Q_SMALL_THRESHOLD      0  /* always */
#define SB_DIV_QR_SMALL_THRESHOLD        17
#define DC_DIV_QR_THRESHOLD              60
#define INV_DIV_QR_THRESHOLD           2444
#define INV_DIVAPPR_Q_N_THRESHOLD        60
#define DC_DIV_Q_THRESHOLD               61
#define INV_DIV_Q_THRESHOLD            1970
#define DC_DIVAPPR_Q_THRESHOLD           32
#define INV_DIVAPPR_Q_THRESHOLD       19406
#define DC_BDIV_QR_THRESHOLD             58
#define DC_BDIV_Q_THRESHOLD              30

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 4 }, { 4, 3 }, { 3, 2 }, { 2, 1 }, { 1, 1 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 19

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 126 seconds */

