/* Generated by tuneup.c, 2009-04-14, system compiler */

#define MUL_KARATSUBA_THRESHOLD          28
#define MUL_TOOM3_THRESHOLD             161
#define MUL_TOOM4_THRESHOLD             567
#define MUL_TOOM7_THRESHOLD             567

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          34
#define SQR_TOOM3_THRESHOLD             218

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD             118
#define MULLOW_MUL_N_THRESHOLD          228

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                102
#define POWM_THRESHOLD                  200

#define GCD_ACCEL_THRESHOLD               3
#define GCDEXT_THRESHOLD                218
#define JACOBI_BASE_METHOD                2

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               0
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD             10
#define GET_STR_PRECOMPUTE_THRESHOLD     11
#define SET_STR_THRESHOLD              8540

#define MUL_FFT_TABLE  { 752, 1696, 3520, 7424, 15360, 45056, 0 }
#define MUL_FFT_MODF_THRESHOLD          976

#define SQR_FFT_TABLE  { 880, 1888, 3904, 7424, 15360, 36864, 0 }
#define SQR_FFT_MODF_THRESHOLD         1008
#define SQR_FFT_THRESHOLD              7040

/* Tuneup completed successfully, took 22 seconds */