/* Generated by tuneup.c, 2009-03-20, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          19
#define MUL_TOOM3_THRESHOLD             109

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          26
#define SQR_TOOM3_THRESHOLD             121

#define MULLOW_BASECASE_THRESHOLD         5
#define MULLOW_DC_THRESHOLD              37
#define MULLOW_MUL_N_THRESHOLD          339

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 50
#define POWM_THRESHOLD                  101

#define GCD_ACCEL_THRESHOLD              54
#define GCDEXT_THRESHOLD                112
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD             12
#define GET_STR_PRECOMPUTE_THRESHOLD     14
#define SET_STR_THRESHOLD              7764

#define MUL_FFT_TABLE  { 496, 1120, 2368, 3840, 11264, 28672, 81920, 327680, 786432, 0 }
#define MUL_FFT_MODF_THRESHOLD          512
#define MUL_FFT_THRESHOLD              3456

#define SQR_FFT_TABLE  { 560, 1248, 2624, 3840, 11264, 28672, 81920, 327680, 786432, 0 }
#define SQR_FFT_MODF_THRESHOLD          576
#define SQR_FFT_THRESHOLD              3456

/* Tuneup completed successfully, took 24 seconds */
