/* Generated by tuneup.c, 2009-04-11, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          19
#define MUL_TOOM3_THRESHOLD              61
#define MUL_TOOM4_THRESHOLD             507
#define MUL_TOOM7_THRESHOLD             638

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD             109

#define MULLOW_BASECASE_THRESHOLD         4
#define MULLOW_DC_THRESHOLD              37
#define MULLOW_MUL_N_THRESHOLD          345

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 56
#define POWM_THRESHOLD                   95

#define GCD_ACCEL_THRESHOLD              38
#define GCDEXT_THRESHOLD                112
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               0
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD              6
#define GET_STR_PRECOMPUTE_THRESHOLD      7
#define SET_STR_THRESHOLD              7764

#define MUL_FFT_TABLE  { 496, 1120, 2240, 3840, 11264, 28672, 81920, 327680, 1310720, 5242880, 12582912, 0 }
#define MUL_FFT_MODF_THRESHOLD          560
#define MUL_FFT_THRESHOLD              9728

#define SQR_FFT_TABLE  { 560, 1184, 2624, 3840, 11264, 28672, 81920, 327680, 786432, 3145728, 12582912, 0 }
#define SQR_FFT_MODF_THRESHOLD          552
#define SQR_FFT_THRESHOLD              3456

/* Tuneup completed successfully, took 327 seconds */
