language: c
sudo: false
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
env:
  - BUILDTOOL=autoconf
  - BUILDTOOL=cmake
addons:
  apt:
    packages:
      - yasm
      - texinfo
script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       brew update;
       brew install yasm;
    fi
  # On OSX, gcc is a wrapper around clang, so use gcc from homebrew
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]] && [[ "${CC}" == "gcc" ]]; then
       brew install gcc;
       brew link --overwrite gcc;
       export CC=gcc;
       export CXX=g++;
    fi
  - $CC --version
  - if [[ "${BUILDTOOL}" == "autoconf" ]]; then
       ./autogen.sh;
       ./configure && make && make check;
    fi
  - if [[ "${BUILDTOOL}" == "cmake" ]]; then
       mkdir build && cd build;
       cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMPIR_GMP=ON -DMPIR_TESTS=ON;
       make -j2 && make test;
    fi
