/* Generated by tuneup.c, 2017-02-14, gcc 4.9 */

#define MUL_KARATSUBA_THRESHOLD          20
#define MUL_TOOM3_THRESHOLD             122
#define MUL_TOOM4_THRESHOLD             202
#define MUL_TOOM8H_THRESHOLD            351

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          38
#define SQR_TOOM3_THRESHOLD             129
#define SQR_TOOM4_THRESHOLD             348
#define SQR_TOOM8_THRESHOLD             414

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                15
#define DIVREM_HENSEL_QR_1_THRESHOLD      9
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD     72

#define MUL_FFT_FULL_THRESHOLD         6976

#define SQR_FFT_FULL_THRESHOLD         3520

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              45
#define MULLOW_MUL_THRESHOLD           3436

#define MULMID_TOOM42_THRESHOLD          21

#define MULHIGH_BASECASE_THRESHOLD       13
#define MULHIGH_DC_THRESHOLD             14
#define MULHIGH_MUL_THRESHOLD          3336

#define MULMOD_2EXPM1_THRESHOLD          18

#define DC_DIV_QR_THRESHOLD              48
#define INV_DIV_QR_THRESHOLD           2130
#define INV_DIVAPPR_Q_N_THRESHOLD        48
#define DC_DIV_Q_THRESHOLD               97
#define INV_DIV_Q_THRESHOLD            1142
#define DC_DIVAPPR_Q_THRESHOLD          221
#define INV_DIVAPPR_Q_THRESHOLD       10764
#define DC_BDIV_QR_THRESHOLD             60
#define DC_BDIV_Q_THRESHOLD             136

#define BINV_NEWTON_THRESHOLD            57
#define REDC_1_TO_REDC_2_THRESHOLD       28
#define REDC_2_TO_REDC_N_THRESHOLD        0  /* always */

#define ROOTREM_THRESHOLD                 6

#define MATRIX22_STRASSEN_THRESHOLD      15
#define HGCD_THRESHOLD                   95
#define HGCD_APPR_THRESHOLD              97
#define HGCD_REDUCE_THRESHOLD          6852
#define GCD_DC_THRESHOLD                706
#define GCDEXT_DC_THRESHOLD             492
#define JACOBI_BASE_METHOD                2

#define GET_STR_DC_THRESHOLD             14
#define GET_STR_PRECOMPUTE_THRESHOLD     20
#define SET_STR_DC_THRESHOLD           1562
#define SET_STR_PRECOMPUTE_THRESHOLD   3100

#define FAC_DSC_THRESHOLD               656
#define FAC_ODD_THRESHOLD                 0  /* always */

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 4, 3 }, { 3, 2 }, { 2, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 19

#define FFT_MULMOD_2EXPP1_CUTOFF 256


/* Tuneup completed successfully, took 75 seconds */
