/* Generated by tuneup.c, 2014-03-19, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD              84
#define MUL_TOOM4_THRESHOLD             166
#define MUL_TOOM8H_THRESHOLD            222

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          22
#define SQR_TOOM3_THRESHOLD              80
#define SQR_TOOM4_THRESHOLD             232
#define SQR_TOOM8_THRESHOLD             309

#define POWM_THRESHOLD                  134

#define HGCD_THRESHOLD                   30
#define GCD_DC_THRESHOLD                502
#define GCDEXT_DC_THRESHOLD             354
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                22
#define DIVREM_HENSEL_QR_1_THRESHOLD      8
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD      9

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             11
#define GET_STR_PRECOMPUTE_THRESHOLD     15
#define SET_STR_DC_THRESHOLD            650
#define SET_STR_PRECOMPUTE_THRESHOLD    773

#define MUL_FFT_FULL_THRESHOLD         3904

#define SQR_FFT_FULL_THRESHOLD         2496

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              16
#define MULLOW_MUL_THRESHOLD           2393

#define MULHIGH_BASECASE_THRESHOLD        8
#define MULHIGH_DC_THRESHOLD             14
#define MULHIGH_MUL_THRESHOLD          2393

#define MULMOD_2EXPM1_THRESHOLD          12

#define FAC_UI_THRESHOLD               1034
#define SB_DIVAPPR_Q_SMALL_THRESHOLD      0  /* always */
#define SB_DIV_QR_SMALL_THRESHOLD         0  /* always */
#define DC_DIV_QR_THRESHOLD              46
#define INV_DIV_QR_THRESHOLD           1589
#define INV_DIVAPPR_Q_N_THRESHOLD        46
#define DC_DIV_Q_THRESHOLD               59
#define INV_DIV_Q_THRESHOLD            1078
#define DC_DIVAPPR_Q_THRESHOLD           19
#define INV_DIVAPPR_Q_THRESHOLD       15352
#define DC_BDIV_QR_THRESHOLD             48
#define DC_BDIV_Q_THRESHOLD              76

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 3, 2 }, { 2, 2 }, { 2, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 3, 3, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 19

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 121 seconds */

