/* Generated by tuneup.c, 2011-12-03, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          19
#define MUL_TOOM3_THRESHOLD              65
#define MUL_TOOM4_THRESHOLD             166
#define MUL_TOOM8H_THRESHOLD            238

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          37
#define SQR_TOOM3_THRESHOLD             106
#define SQR_TOOM4_THRESHOLD             294
#define SQR_TOOM8_THRESHOLD             294

#define POWM_THRESHOLD                   62

#define HGCD_THRESHOLD                   46
#define GCD_DC_THRESHOLD               1391
#define GCDEXT_DC_THRESHOLD             960
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                19
#define DIVREM_HENSEL_QR_1_THRESHOLD      8
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD     22

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             11
#define GET_STR_PRECOMPUTE_THRESHOLD     17
#define SET_STR_DC_THRESHOLD           6847
#define SET_STR_PRECOMPUTE_THRESHOLD   6847

#define MUL_FFT_FULL_THRESHOLD         2240

#define SQR_FFT_FULL_THRESHOLD         1984

#define MULLOW_BASECASE_THRESHOLD        17
#define MULLOW_DC_THRESHOLD              17
#define MULLOW_MUL_THRESHOLD           3402

#define MULHIGH_BASECASE_THRESHOLD       18
#define MULHIGH_DC_THRESHOLD             18
#define MULHIGH_MUL_THRESHOLD          3754

#define MULMOD_2EXPM1_THRESHOLD          12

#define FAC_UI_THRESHOLD              12884
#define DC_DIV_QR_THRESHOLD              52
#define DC_DIVAPPR_Q_N_THRESHOLD        138
#define INV_DIV_QR_THRESHOLD           2747
#define INV_DIVAPPR_Q_N_THRESHOLD       138
#define DC_DIV_Q_THRESHOLD              148
#define INV_DIV_Q_THRESHOLD            3762
#define DC_DIVAPPR_Q_THRESHOLD          138
#define INV_DIVAPPR_Q_THRESHOLD        8893
#define DC_BDIV_QR_THRESHOLD             48
#define DC_BDIV_Q_THRESHOLD              38
/* Tuneup completed successfully, took 720 seconds */
