/* Generated by tuneup.c, 2011-06-05, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          18
#define MUL_TOOM3_THRESHOLD              53
#define MUL_TOOM4_THRESHOLD             410
#define MUL_TOOM8H_THRESHOLD            410

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD              89
#define SQR_TOOM4_THRESHOLD             686
#define SQR_TOOM8_THRESHOLD             686

#define POWM_THRESHOLD                  166

#define GCD_THRESHOLD                   582
#define GCDEXT_THRESHOLD                818
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD               996
#define DIVREM_HENSEL_QR_1_THRESHOLD     15
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD     19
#define DIVREM_EUCLID_HENSEL_THRESHOLD     10

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD             16
#define GET_STR_PRECOMPUTE_THRESHOLD     25
#define SET_STR_DC_THRESHOLD            193
#define SET_STR_PRECOMPUTE_THRESHOLD    324

#define MUL_FFT_TABLE  { 336, 800, 2112, 2816, 7168, 20480, 81920, 327680, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          280
#define MUL_FFT_FULL_THRESHOLD         2240

#define SQR_FFT_TABLE  { 368, 800, 2112, 2816, 7168, 28672, 81920, 327680, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          360
#define SQR_FFT_FULL_THRESHOLD         2240

#define MULLOW_BASECASE_THRESHOLD         5
#define MULLOW_DC_THRESHOLD              52
#define MULLOW_MUL_THRESHOLD           3504

#define MULHIGH_BASECASE_THRESHOLD        8
#define MULHIGH_DC_THRESHOLD             38
#define MULHIGH_MUL_THRESHOLD          3470

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD              13948
#define DC_DIV_QR_THRESHOLD              70
#define DC_DIVAPPR_Q_N_THRESHOLD        112
#define INV_DIV_QR_THRESHOLD           3152
#define INV_DIVAPPR_Q_N_THRESHOLD       112
#define DC_DIV_Q_THRESHOLD              165
#define INV_DIV_Q_THRESHOLD            5365
#define DC_DIVAPPR_Q_THRESHOLD          138
#define INV_DIVAPPR_Q_THRESHOLD       13019
#define DC_BDIV_QR_THRESHOLD             70
#define DC_BDIV_Q_THRESHOLD              62
/* Tuneup completed successfully, took 683 seconds */
