/* Generated by tuneup.c, 2009-04-01, system compiler */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD             114
#define MUL_TOOM4_THRESHOLD             180
#define MUL_TOOM7_THRESHOLD             587

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD             177

#define MULLOW_BASECASE_THRESHOLD         6
#define MULLOW_DC_THRESHOLD              80
#define MULLOW_MUL_N_THRESHOLD          378

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 94
#define POWM_THRESHOLD                   95

#define GCD_ACCEL_THRESHOLD               8
#define GCDEXT_THRESHOLD                202
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               0
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD             19
#define GET_STR_PRECOMPUTE_THRESHOLD     22
#define SET_STR_THRESHOLD              7764

#define MUL_FFT_TABLE  { 464, 1184, 2368, 3840, 9216, 28672, 0 }
#define MUL_FFT_MODF_THRESHOLD          480
#define MUL_FFT_THRESHOLD              3712

#define SQR_FFT_TABLE  { 592, 1312, 2624, 4864, 11264, 28672, 0 }
#define SQR_FFT_MODF_THRESHOLD          584
#define SQR_FFT_THRESHOLD              3712

/* Tuneup completed successfully, took 12 seconds */