/* Generated by tuneup.c, 2009-03-08, system compiler */

#define MUL_KARATSUBA_THRESHOLD          18
#define MUL_TOOM3_THRESHOLD             121

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD             145

#define MULLOW_BASECASE_THRESHOLD         6
#define MULLOW_DC_THRESHOLD              83
#define MULLOW_MUL_N_THRESHOLD          399

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 98
#define POWM_THRESHOLD                   97

#define GCD_ACCEL_THRESHOLD              20
#define GCDEXT_THRESHOLD                161
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD             20
#define GET_STR_PRECOMPUTE_THRESHOLD     25
#define SET_STR_THRESHOLD              7764

#define MUL_FFT_TABLE  { 464, 1120, 2368, 3840, 9216, 28672, 0 }
#define MUL_FFT_MODF_THRESHOLD          480
#define MUL_FFT_THRESHOLD              2944

#define SQR_FFT_TABLE  { 592, 1120, 2368, 3840, 11264, 36864, 0 }
#define SQR_FFT_MODF_THRESHOLD          608
#define SQR_FFT_THRESHOLD              3456

/* Tuneup completed successfully, took 11 seconds */