/* Generated by tuneup.c, 2012-10-23, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          22
#define MUL_TOOM3_THRESHOLD             128
#define MUL_TOOM4_THRESHOLD             190
#define MUL_TOOM8H_THRESHOLD            303

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          62
#define SQR_TOOM3_THRESHOLD             126
#define SQR_TOOM4_THRESHOLD             321
#define SQR_TOOM8_THRESHOLD             348

#define POWM_THRESHOLD                  984

#define HGCD_THRESHOLD                   50
#define GCD_DC_THRESHOLD               1720
#define GCDEXT_DC_THRESHOLD             354
#define JACOBI_BASE_METHOD                1

#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* native */
#define DIVREM_2_THRESHOLD               21
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD               282
#define MOD_1_2_THRESHOLD               996
#define MOD_1_3_THRESHOLD               996
#define DIVREM_HENSEL_QR_1_THRESHOLD      2
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      4
#define DIVREM_EUCLID_HENSEL_THRESHOLD     13

#define ROOTREM_THRESHOLD                 7

#define GET_STR_DC_THRESHOLD             15
#define GET_STR_PRECOMPUTE_THRESHOLD     25
#define SET_STR_DC_THRESHOLD            272
#define SET_STR_PRECOMPUTE_THRESHOLD    314

#define MUL_FFT_FULL_THRESHOLD         5376

#define SQR_FFT_FULL_THRESHOLD         7936

#define MULLOW_BASECASE_THRESHOLD         7
#define MULLOW_DC_THRESHOLD              42
#define MULLOW_MUL_THRESHOLD            105

#define MULHIGH_BASECASE_THRESHOLD        9
#define MULHIGH_DC_THRESHOLD             38
#define MULHIGH_MUL_THRESHOLD          2512

#define MULMOD_2EXPM1_THRESHOLD          22

#define FAC_UI_THRESHOLD               1024
#define DC_DIV_QR_THRESHOLD              64
#define DC_DIVAPPR_Q_N_THRESHOLD         60
#define INV_DIV_QR_THRESHOLD             73
#define INV_DIVAPPR_Q_N_THRESHOLD        60
#define DC_DIV_Q_THRESHOLD              174
#define INV_DIV_Q_THRESHOLD            1258
#define DC_DIVAPPR_Q_THRESHOLD           97
#define INV_DIVAPPR_Q_THRESHOLD        6686
#define DC_BDIV_QR_THRESHOLD            268
#define DC_BDIV_Q_THRESHOLD              49

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 3, 3 }, { 3, 1 }, { 2, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 3, 4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 15

#define FFT_MULMOD_2EXPP1_CUTOFF 256


/* Tuneup completed successfully, took 922 seconds */
