/* Generated by tuneup.c, 2010-03-24, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          22
#define MUL_TOOM3_THRESHOLD             140
#define MUL_TOOM4_THRESHOLD             212
#define MUL_TOOM8H_THRESHOLD            286

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          51
#define SQR_TOOM3_THRESHOLD             116
#define SQR_TOOM4_THRESHOLD             298
#define SQR_TOOM8_THRESHOLD             366

#define POWM_THRESHOLD                  984

#define GCD_ACCEL_THRESHOLD              18
#define GCDEXT_THRESHOLD                 88
#define JACOBI_BASE_METHOD                1

#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* native */
#define DIVREM_2_THRESHOLD               23
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                80
#define MOD_1_2_THRESHOLD                94
#define MOD_1_3_THRESHOLD                95
#define DIVREM_HENSEL_QR_1_THRESHOLD      8
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      4
#define DIVREM_EUCLID_HENSEL_THRESHOLD     27

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD             13
#define GET_STR_PRECOMPUTE_THRESHOLD     20
#define SET_STR_DC_THRESHOLD            446
#define SET_STR_PRECOMPUTE_THRESHOLD    744

#define MUL_FFT_TABLE  { 400, 1120, 1408, 3584, 10240, 40960, 163840, 655360, 2621440, 10485760, 0 }
#define MUL_FFT_MODF_THRESHOLD          432
#define MUL_FFT_FULL_THRESHOLD         1664

#define SQR_FFT_TABLE  { 432, 992, 1920, 3584, 10240, 40960, 163840, 655360, 2621440, 10485760, 0 }
#define SQR_FFT_MODF_THRESHOLD          400
#define SQR_FFT_FULL_THRESHOLD         2176

#define MULLOW_BASECASE_THRESHOLD        11
#define MULLOW_DC_THRESHOLD              64
#define MULLOW_MUL_THRESHOLD            112

#define MULHIGH_BASECASE_THRESHOLD        6
#define MULHIGH_DC_THRESHOLD             45
#define MULHIGH_MUL_THRESHOLD          3271

#define MULMOD_2EXPM1_THRESHOLD          20

#define FAC_UI_THRESHOLD               3366
#define DC_DIV_QR_THRESHOLD              42
#define DC_DIVAPPR_Q_N_THRESHOLD         48
#define INV_DIV_QR_THRESHOLD           3279
#define INV_DIVAPPR_Q_N_THRESHOLD        48
#define DC_DIV_Q_THRESHOLD              205
#define INV_DIV_Q_THRESHOLD            2304
#define DC_DIVAPPR_Q_THRESHOLD          186
#define INV_DIVAPPR_Q_THRESHOLD        4644
#define DC_BDIV_QR_THRESHOLD             60
#define DC_BDIV_Q_THRESHOLD              49
/* Tuneup completed successfully, took 564 seconds */
