/* Generated by tuneup.c, 2011-11-22, gcc 4.5 */

#define MUL_KARATSUBA_THRESHOLD          14
#define MUL_TOOM3_THRESHOLD              75
#define MUL_TOOM4_THRESHOLD             214
#define MUL_TOOM8H_THRESHOLD            292

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          27
#define SQR_TOOM3_THRESHOLD              89
#define SQR_TOOM4_THRESHOLD             704
#define SQR_TOOM8_THRESHOLD             704

#define POWM_THRESHOLD                  158

#define HGCD_THRESHOLD                   38
#define GCD_DC_THRESHOLD               1502
#define GCDEXT_DC_THRESHOLD            1015
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 6
#define MOD_1_3_THRESHOLD               122
#define DIVREM_HENSEL_QR_1_THRESHOLD     15
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD     19
#define DIVREM_EUCLID_HENSEL_THRESHOLD     25

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD             16
#define GET_STR_PRECOMPUTE_THRESHOLD     26
#define SET_STR_DC_THRESHOLD            191
#define SET_STR_PRECOMPUTE_THRESHOLD    591

#define MUL_FFT_TABLE  { 368, 736, 1984, 2304, 7168, 28672, 81920, 327680, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          384
#define MUL_FFT_FULL_THRESHOLD         2112

#define SQR_FFT_TABLE  { 400, 800, 2112, 2816, 7168, 28672, 81920, 327680, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          376
#define SQR_FFT_FULL_THRESHOLD         2240

#define MULLOW_BASECASE_THRESHOLD         5
#define MULLOW_DC_THRESHOLD              32
#define MULLOW_MUL_THRESHOLD           3176

#define MULHIGH_BASECASE_THRESHOLD        8
#define MULHIGH_DC_THRESHOLD             33
#define MULHIGH_MUL_THRESHOLD          3176

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD              32756
#define DC_DIV_QR_THRESHOLD              56
#define DC_DIVAPPR_Q_N_THRESHOLD        110
#define INV_DIV_QR_THRESHOLD           3152
#define INV_DIVAPPR_Q_N_THRESHOLD       110
#define DC_DIV_Q_THRESHOLD              156
#define INV_DIV_Q_THRESHOLD            4765
#define DC_DIVAPPR_Q_THRESHOLD          126
#define INV_DIVAPPR_Q_THRESHOLD       13019
#define DC_BDIV_QR_THRESHOLD             54
#define DC_BDIV_Q_THRESHOLD              62
/* Tuneup completed successfully, took 732 seconds */
