@echo off
echo /* generated by gen_config_h.bat */ >cfg.h
for /f  %%a in (%1cfg.h) do (if "%%a" NEQ "" (echo #define HAVE_NATIVE_%%a 1 >>cfg.h))

type ..\cfg.h >>cfg.h
call ..\out_copy_rename cfg.h ..\..\ config.h
