# $Id: Makefile.inc 1782 2007-02-21 06:45:39Z peter $

TESTS += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.asm
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.hex
