/* Generated by tuneup.c, 2009-01-04, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          31
#define MUL_TOOM3_THRESHOLD              90

#define SQR_BASECASE_THRESHOLD            0  /* always */
#define SQR_KARATSUBA_THRESHOLD          52
#define SQR_TOOM3_THRESHOLD             137

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              34
#define MULLOW_MUL_N_THRESHOLD          537

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 66
#define POWM_THRESHOLD                  134

#define GCD_ACCEL_THRESHOLD              54
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             18
#define GET_STR_PRECOMPUTE_THRESHOLD     21
#define SET_STR_THRESHOLD              7764

#define MUL_FFT_TABLE  { 592, 1440, 2880, 5888, 11264, 36864, 114688, 327680, 0 }
#define MUL_FFT_MODF_THRESHOLD          720
#define MUL_FFT_THRESHOLD              4736

#define SQR_FFT_TABLE  { 560, 1248, 2368, 4864, 11264, 28672, 81920, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          576
#define SQR_FFT_THRESHOLD              3968

/* Tuneup completed successfully, took 21 seconds */
