/* Generated by tuneup.c, 2009-02-27, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          28
#define MUL_TOOM3_THRESHOLD              85

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          36
#define SQR_TOOM3_THRESHOLD             129

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              34
#define MULLOW_MUL_N_THRESHOLD          486

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 62
#define POWM_THRESHOLD                  134

#define GCD_ACCEL_THRESHOLD              67
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             20
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_THRESHOLD              7059

#define MUL_FFT_TABLE  { 656, 1696, 3392, 5888, 15360, 36864, 114688, 327680, 1310720, 5242880, 12582912, 0 }
#define MUL_FFT_MODF_THRESHOLD          752
#define MUL_FFT_THRESHOLD              5760

#define SQR_FFT_TABLE  { 720, 1696, 3392, 5888, 15360, 45056, 114688, 327680, 1310720, 5242880, 12582912, 0 }
#define SQR_FFT_MODF_THRESHOLD          848
#define SQR_FFT_THRESHOLD              5504

/* Tuneup completed successfully, took 312 seconds */
