/* Generated by tuneup.c, 2009-10-08, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          19
#define MUL_TOOM3_THRESHOLD              50
#define MUL_TOOM4_THRESHOLD             268
#define MUL_TOOM7_THRESHOLD             587

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          24
#define SQR_TOOM3_THRESHOLD              85
#define SQR_TOOM4_THRESHOLD             133
#define SQR_TOOM7_THRESHOLD             170

#define MULLOW_BASECASE_THRESHOLD        17
#define MULLOW_DC_THRESHOLD              17
#define MULLOW_MUL_THRESHOLD           5620

#define MULHIGH_BASECASE_THRESHOLD       18
#define MULHIGH_DC_THRESHOLD             18
#define MULHIGH_MUL_THRESHOLD          5620

#define MULMOD_2EXPM1_THRESHOLD          16

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 54
#define POWM_THRESHOLD                   73
#define FAC_UI_THRESHOLD               8501

#define GCD_ACCEL_THRESHOLD              43
#define GCDEXT_THRESHOLD                111
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD            MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                17
#define DIVREM_HENSEL_QR_1_THRESHOLD      7
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD     16

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD              5
#define GET_STR_PRECOMPUTE_THRESHOLD      7
#define SET_STR_THRESHOLD              6418

#define MUL_FFT_TABLE  { 400, 800, 2240, 2816, 7168, 20480, 81920, 327680, 0 }
#define MUL_FFT_MODF_THRESHOLD          368
#define MUL_FFT_THRESHOLD              2944

#define SQR_FFT_TABLE  { 368, 800, 2112, 2816, 7168, 20480, 81920, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          264
#define SQR_FFT_THRESHOLD              2432

/* Tuneup completed successfully, took 54 seconds */
