/* Generated by tuneup.c, 2011-11-22, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD              90
#define MUL_TOOM4_THRESHOLD             166
#define MUL_TOOM8H_THRESHOLD            270

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          31
#define SQR_TOOM3_THRESHOLD              89
#define SQR_TOOM4_THRESHOLD             248
#define SQR_TOOM8_THRESHOLD             321

#define POWM_THRESHOLD                  107

#define HGCD_THRESHOLD                  178
#define GCD_DC_THRESHOLD               2464
#define GCDEXT_DC_THRESHOLD            1788
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                17
#define DIVREM_HENSEL_QR_1_THRESHOLD     14
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      7
#define DIVREM_EUCLID_HENSEL_THRESHOLD    108

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             15
#define GET_STR_PRECOMPUTE_THRESHOLD     21
#define SET_STR_DC_THRESHOLD           6390
#define SET_STR_PRECOMPUTE_THRESHOLD   6517

#define MUL_FFT_FULL_THRESHOLD         1984

#define SQR_FFT_FULL_THRESHOLD         1856

#define MULLOW_BASECASE_THRESHOLD         7
#define MULLOW_DC_THRESHOLD              11
#define MULLOW_MUL_THRESHOLD           3207

#define MULHIGH_BASECASE_THRESHOLD       17
#define MULHIGH_DC_THRESHOLD             17
#define MULHIGH_MUL_THRESHOLD          3207

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD              12884
#define DC_DIV_QR_THRESHOLD              36
#define DC_DIVAPPR_Q_N_THRESHOLD         57
#define INV_DIV_QR_THRESHOLD           2492
#define INV_DIVAPPR_Q_N_THRESHOLD        57
#define DC_DIV_Q_THRESHOLD               97
#define INV_DIV_Q_THRESHOLD            3547
#define DC_DIVAPPR_Q_THRESHOLD           73
#define INV_DIVAPPR_Q_THRESHOLD        7350
#define DC_BDIV_QR_THRESHOLD             36
#define DC_BDIV_Q_THRESHOLD              11
/* Tuneup completed successfully, took 351 seconds */
