/* Generated by tuneup.c, 2011-11-23, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          52
#define MUL_TOOM3_THRESHOLD             258
#define MUL_TOOM4_THRESHOLD             562
#define MUL_TOOM8H_THRESHOLD            562

#define SQR_BASECASE_THRESHOLD           30
#define SQR_KARATSUBA_THRESHOLD         127
#define SQR_TOOM3_THRESHOLD             238
#define SQR_TOOM4_THRESHOLD             996
#define SQR_TOOM8_THRESHOLD             996

#define POWM_THRESHOLD                  984

#define HGCD_THRESHOLD                  232
#define GCD_DC_THRESHOLD               1365
#define GCDEXT_DC_THRESHOLD            1913
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* preinv always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* preinv always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                11
#define DIVREM_HENSEL_QR_1_THRESHOLD      4
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      7
#define DIVREM_EUCLID_HENSEL_THRESHOLD      9

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             16
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           1204
#define SET_STR_PRECOMPUTE_THRESHOLD  21712

#define MUL_FFT_FULL_THRESHOLD         3328

#define SQR_FFT_FULL_THRESHOLD         3328

#define MULLOW_BASECASE_THRESHOLD        29
#define MULLOW_DC_THRESHOLD              29
#define MULLOW_MUL_THRESHOLD           4849

#define MULHIGH_BASECASE_THRESHOLD       41
#define MULHIGH_DC_THRESHOLD             41
#define MULHIGH_MUL_THRESHOLD          4849

#define MULMOD_2EXPM1_THRESHOLD          34

#define FAC_UI_THRESHOLD              32756
#define DC_DIV_QR_THRESHOLD              31
#define DC_DIVAPPR_Q_N_THRESHOLD        205
#define INV_DIV_QR_THRESHOLD           1718
#define INV_DIVAPPR_Q_N_THRESHOLD       205
#define DC_DIV_Q_THRESHOLD              245
#define INV_DIV_Q_THRESHOLD             595
#define DC_DIVAPPR_Q_THRESHOLD          201
#define INV_DIVAPPR_Q_THRESHOLD        2347
#define DC_BDIV_QR_THRESHOLD             92
#define DC_BDIV_Q_THRESHOLD             104
/* Tuneup completed successfully, took 672 seconds */
