/* Generated by tuneup.c, 2010-03-24, gcc 4.1 */

#define MUL_KARATSUBA_THRESHOLD          48
#define MUL_TOOM3_THRESHOLD             186
#define MUL_TOOM4_THRESHOLD             858
#define MUL_TOOM8H_THRESHOLD            858

#define SQR_BASECASE_THRESHOLD           28
#define SQR_KARATSUBA_THRESHOLD         119
#define SQR_TOOM3_THRESHOLD             210
#define SQR_TOOM4_THRESHOLD             996
#define SQR_TOOM8_THRESHOLD             996

#define POWM_THRESHOLD                  984

#define GCD_ACCEL_THRESHOLD              76
#define GCDEXT_THRESHOLD                102
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* preinv always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* preinv always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 6
#define MOD_1_3_THRESHOLD                17
#define DIVREM_HENSEL_QR_1_THRESHOLD      6
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD     10

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             16
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           1204
#define SET_STR_PRECOMPUTE_THRESHOLD   6767

#define MUL_FFT_TABLE  { 496, 992, 2752, 3328, 9216, 28672, 81920, 327680, 1310720, 7340032, 20971520, 83886080, 0 }
#define MUL_FFT_MODF_THRESHOLD          440
#define MUL_FFT_FULL_THRESHOLD         3328

#define SQR_FFT_TABLE  { 528, 1120, 2624, 3840, 11264, 28672, 81920, 327680, 1310720, 7340032, 20971520, 83886080, 0 }
#define SQR_FFT_MODF_THRESHOLD          528
#define SQR_FFT_FULL_THRESHOLD         3328

#define MULLOW_BASECASE_THRESHOLD        29
#define MULLOW_DC_THRESHOLD              29
#define MULLOW_MUL_THRESHOLD           4849

#define MULHIGH_BASECASE_THRESHOLD       41
#define MULHIGH_DC_THRESHOLD             41
#define MULHIGH_MUL_THRESHOLD          4849

#define MULMOD_2EXPM1_THRESHOLD          34

#define FAC_UI_THRESHOLD              32756
#define DC_DIV_QR_THRESHOLD              30
#define DC_DIVAPPR_Q_N_THRESHOLD        183
#define INV_DIV_QR_THRESHOLD           1078
#define INV_DIVAPPR_Q_N_THRESHOLD       183
#define DC_DIV_Q_THRESHOLD              245
#define INV_DIV_Q_THRESHOLD            1164
#define DC_DIVAPPR_Q_THRESHOLD          201
#define INV_DIVAPPR_Q_THRESHOLD        3777
#define DC_BDIV_QR_THRESHOLD             92
#define DC_BDIV_Q_THRESHOLD              96
/* Tuneup completed successfully, took 4948 seconds */
