/* Generated by tuneup.c, 2012-10-24, gcc 4.3 */

#define MUL_KARATSUBA_THRESHOLD          22
#define MUL_TOOM3_THRESHOLD             132
#define MUL_TOOM4_THRESHOLD             360
#define MUL_TOOM8H_THRESHOLD            587

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          43
#define SQR_TOOM3_THRESHOLD             127
#define SQR_TOOM4_THRESHOLD             532
#define SQR_TOOM8_THRESHOLD             680

#define POWM_THRESHOLD                  339

#define HGCD_THRESHOLD                   67
#define GCD_DC_THRESHOLD               2995
#define GCDEXT_DC_THRESHOLD            2301
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD          MP_SIZE_T_MAX  /* never */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                 7
#define MOD_1_3_THRESHOLD                32
#define DIVREM_HENSEL_QR_1_THRESHOLD      5
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      8
#define DIVREM_EUCLID_HENSEL_THRESHOLD     11

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             14
#define GET_STR_PRECOMPUTE_THRESHOLD     21
#define SET_STR_DC_THRESHOLD           7941
#define SET_STR_PRECOMPUTE_THRESHOLD  99885

#define MUL_FFT_FULL_THRESHOLD         7104

#define SQR_FFT_FULL_THRESHOLD         7232

#define MULLOW_BASECASE_THRESHOLD        18
#define MULLOW_DC_THRESHOLD              18
#define MULLOW_MUL_THRESHOLD           5732

#define MULHIGH_BASECASE_THRESHOLD       13
#define MULHIGH_DC_THRESHOLD             33
#define MULHIGH_MUL_THRESHOLD          5732

#define MULMOD_2EXPM1_THRESHOLD          18

#define FAC_UI_THRESHOLD               1024
#define DC_DIV_QR_THRESHOLD             298
#define DC_DIVAPPR_Q_N_THRESHOLD        148
#define INV_DIV_QR_THRESHOLD            693
#define INV_DIVAPPR_Q_N_THRESHOLD       148
#define DC_DIV_Q_THRESHOLD              189
#define INV_DIV_Q_THRESHOLD            7356
#define DC_DIVAPPR_Q_THRESHOLD          162
#define INV_DIVAPPR_Q_THRESHOLD       18500
#define DC_BDIV_QR_THRESHOLD            278
#define DC_BDIV_Q_THRESHOLD              35

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 4 }, { 3, 3 }, { 3, 2 }, { 2, 2 }, { 2, 1 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 23

#define FFT_MULMOD_2EXPP1_CUTOFF 256


/* Tuneup completed successfully, took 207 seconds */
