/* Generated by tuneup.c, 2009-10-08, gcc 4.3 */

#define MUL_KARATSUBA_THRESHOLD          24
#define MUL_TOOM3_THRESHOLD              67
#define MUL_TOOM4_THRESHOLD             354
#define MUL_TOOM7_THRESHOLD             587

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          35
#define SQR_TOOM3_THRESHOLD             117
#define SQR_TOOM4_THRESHOLD             120
#define SQR_TOOM7_THRESHOLD             121

#define MULLOW_BASECASE_THRESHOLD         5
#define MULLOW_DC_THRESHOLD              33
#define MULLOW_MUL_THRESHOLD           6647

#define MULHIGH_BASECASE_THRESHOLD       13
#define MULHIGH_DC_THRESHOLD             17
#define MULHIGH_MUL_THRESHOLD          6647

#define MULMOD_2EXPM1_THRESHOLD          18

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 60
#define POWM_THRESHOLD                  138
#define FAC_UI_THRESHOLD              14087

#define GCD_ACCEL_THRESHOLD              58
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD            MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                10
#define MOD_1_3_THRESHOLD                29
#define DIVREM_HENSEL_QR_1_THRESHOLD      7
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      6
#define DIVREM_EUCLID_HENSEL_THRESHOLD      8

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD              3
#define GET_STR_PRECOMPUTE_THRESHOLD      7
#define SET_STR_THRESHOLD              4385

#define MUL_FFT_TABLE  { 432, 992, 2240, 2816, 7168, 28672, 114688, 327680, 0 }
#define MUL_FFT_MODF_THRESHOLD          432
#define MUL_FFT_THRESHOLD              4864

#define SQR_FFT_TABLE  { 432, 928, 2240, 2816, 7168, 28672, 114688, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          432
#define SQR_FFT_THRESHOLD              4864

/* Tuneup completed successfully, took 33 seconds */
