/* Generated by tuneup.c, 2010-03-24, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          22
#define MUL_TOOM3_THRESHOLD              78
#define MUL_TOOM4_THRESHOLD             396
#define MUL_TOOM8H_THRESHOLD            396

#define SQR_BASECASE_THRESHOLD            8
#define SQR_KARATSUBA_THRESHOLD          55
#define SQR_TOOM3_THRESHOLD              81
#define SQR_TOOM4_THRESHOLD             414
#define SQR_TOOM8_THRESHOLD             414

#define POWM_THRESHOLD                  984

#define GCD_ACCEL_THRESHOLD              30
#define GCDEXT_THRESHOLD                 27
#define JACOBI_BASE_METHOD                2

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD          MP_SIZE_T_MAX  /* never */
#define MOD_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  0
#define DIVREM_2_THRESHOLD            MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                24
#define MOD_1_2_THRESHOLD                24
#define MOD_1_3_THRESHOLD               115
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD     95

#define ROOTREM_THRESHOLD                 3

#define GET_STR_DC_THRESHOLD             15
#define GET_STR_PRECOMPUTE_THRESHOLD     29
#define SET_STR_DC_THRESHOLD            244
#define SET_STR_PRECOMPUTE_THRESHOLD    282

#define MUL_FFT_TABLE  { 240, 352, 960, 1280, 5120, 20480, 81920, 196608, 1310720, 5242880, 12582912, 0 }
#define MUL_FFT_MODF_THRESHOLD          216
#define MUL_FFT_FULL_THRESHOLD         1056

#define SQR_FFT_TABLE  { 240, 416, 1088, 1792, 5120, 20480, 81920, 196608, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          216
#define SQR_FFT_FULL_THRESHOLD         1184

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              12
#define MULLOW_MUL_THRESHOLD           1623

#define MULHIGH_BASECASE_THRESHOLD        4
#define MULHIGH_DC_THRESHOLD             11
#define MULHIGH_MUL_THRESHOLD          1623

#define MULMOD_2EXPM1_THRESHOLD          10

#define FAC_UI_THRESHOLD               2687
#define DC_DIV_QR_THRESHOLD              10
#define DC_DIVAPPR_Q_N_THRESHOLD         41
#define INV_DIV_QR_THRESHOLD           1652
#define INV_DIVAPPR_Q_N_THRESHOLD        41
#define DC_DIV_Q_THRESHOLD               75
#define INV_DIV_Q_THRESHOLD            1652
#define DC_DIVAPPR_Q_THRESHOLD           55
#define INV_DIVAPPR_Q_THRESHOLD        3679
#define DC_BDIV_QR_THRESHOLD             18
#define DC_BDIV_Q_THRESHOLD              14
/* Tuneup completed successfully, took 8333 seconds */
