/* Generated by tuneup.c, 2012-10-23, gcc 4.7 */

#define MUL_KARATSUBA_THRESHOLD          34
#define MUL_TOOM3_THRESHOLD              97
#define MUL_TOOM4_THRESHOLD             426
#define MUL_TOOM8H_THRESHOLD            426

#define SQR_BASECASE_THRESHOLD           11
#define SQR_KARATSUBA_THRESHOLD          68
#define SQR_TOOM3_THRESHOLD              99
#define SQR_TOOM4_THRESHOLD             507
#define SQR_TOOM8_THRESHOLD             507

#define POWM_THRESHOLD                  984

#define HGCD_THRESHOLD                   43
#define GCD_DC_THRESHOLD                746
#define GCDEXT_DC_THRESHOLD             572
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD           3
#define DIVREM_1_UNNORM_THRESHOLD         3
#define MOD_1_NORM_THRESHOLD              3
#define MOD_1_UNNORM_THRESHOLD            3
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                12
#define MOD_1_2_THRESHOLD                12
#define MOD_1_3_THRESHOLD               996
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD    119

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             12
#define GET_STR_PRECOMPUTE_THRESHOLD     18
#define SET_STR_DC_THRESHOLD            290
#define SET_STR_PRECOMPUTE_THRESHOLD   2657

#define MUL_FFT_FULL_THRESHOLD         2016

#define SQR_FFT_FULL_THRESHOLD         2016

#define MULLOW_BASECASE_THRESHOLD        30
#define MULLOW_DC_THRESHOLD              30
#define MULLOW_MUL_THRESHOLD           2192

#define MULHIGH_BASECASE_THRESHOLD       44
#define MULHIGH_DC_THRESHOLD             44
#define MULHIGH_MUL_THRESHOLD          1085

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD               1074
#define DC_DIV_QR_THRESHOLD              26
#define DC_DIVAPPR_Q_N_THRESHOLD         94
#define INV_DIV_QR_THRESHOLD            150
#define INV_DIVAPPR_Q_N_THRESHOLD        94
#define DC_DIV_Q_THRESHOLD               22
#define INV_DIV_Q_THRESHOLD             680
#define DC_DIVAPPR_Q_THRESHOLD           24
#define INV_DIVAPPR_Q_THRESHOLD        2514
#define DC_BDIV_QR_THRESHOLD            100
#define DC_BDIV_Q_THRESHOLD              44

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 3, 2 }, { 2, 1 }, { 1, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 23

#define FFT_MULMOD_2EXPP1_CUTOFF 128

/* tuneup crashed, used k8 MULMOD_TAB values */