/* Generated by tuneup.c, 2011-12-03, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          34
#define MUL_TOOM3_THRESHOLD              97
#define MUL_TOOM4_THRESHOLD             438
#define MUL_TOOM8H_THRESHOLD            438

#define SQR_BASECASE_THRESHOLD           11
#define SQR_KARATSUBA_THRESHOLD          68
#define SQR_TOOM3_THRESHOLD              95
#define SQR_TOOM4_THRESHOLD             494
#define SQR_TOOM8_THRESHOLD             494

#define POWM_THRESHOLD                  984

#define HGCD_THRESHOLD                  156
#define GCD_DC_THRESHOLD                527
#define GCDEXT_DC_THRESHOLD             454
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD           3
#define DIVREM_1_UNNORM_THRESHOLD         3
#define MOD_1_NORM_THRESHOLD              3
#define MOD_1_UNNORM_THRESHOLD            3
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                10
#define MOD_1_2_THRESHOLD                10
#define MOD_1_3_THRESHOLD                23
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD     40

#define ROOTREM_THRESHOLD                 3

#define GET_STR_DC_THRESHOLD             13
#define GET_STR_PRECOMPUTE_THRESHOLD     18
#define SET_STR_DC_THRESHOLD            290
#define SET_STR_PRECOMPUTE_THRESHOLD   1394

#define MUL_FFT_FULL_THRESHOLD         1312

#define SQR_FFT_FULL_THRESHOLD         1440

#define MULLOW_BASECASE_THRESHOLD        30
#define MULLOW_DC_THRESHOLD              30
#define MULLOW_MUL_THRESHOLD           1877

#define MULHIGH_BASECASE_THRESHOLD       42
#define MULHIGH_DC_THRESHOLD             42
#define MULHIGH_MUL_THRESHOLD          1877

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD              12757
#define DC_DIV_QR_THRESHOLD              17
#define DC_DIVAPPR_Q_N_THRESHOLD        122
#define INV_DIV_QR_THRESHOLD            693
#define INV_DIVAPPR_Q_N_THRESHOLD       122
#define DC_DIV_Q_THRESHOLD              180
#define INV_DIV_Q_THRESHOLD             595
#define DC_DIVAPPR_Q_THRESHOLD          118
#define INV_DIVAPPR_Q_THRESHOLD        1975
#define DC_BDIV_QR_THRESHOLD             28
#define DC_BDIV_Q_THRESHOLD              84
/* Tuneup completed successfully, took 2566 seconds */
