/* Generated by tuneup.c, 2009-10-08, gcc 4.3 */

#define MUL_KARATSUBA_THRESHOLD          26
#define MUL_TOOM3_THRESHOLD              90
#define MUL_TOOM4_THRESHOLD             248
#define MUL_TOOM7_THRESHOLD             315

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          50
#define SQR_TOOM3_THRESHOLD              95
#define SQR_TOOM4_THRESHOLD              95
#define SQR_TOOM7_THRESHOLD             135

#define MULLOW_BASECASE_THRESHOLD         9
#define MULLOW_DC_THRESHOLD              48
#define MULLOW_MUL_THRESHOLD           5143

#define MULHIGH_BASECASE_THRESHOLD       17
#define MULHIGH_DC_THRESHOLD             22
#define MULHIGH_MUL_THRESHOLD          3539

#define MULMOD_2EXPM1_THRESHOLD          20

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                100
#define POWM_THRESHOLD                  128
#define FAC_UI_THRESHOLD               3570

#define GCD_ACCEL_THRESHOLD              47
#define GCDEXT_THRESHOLD                 33
#define JACOBI_BASE_METHOD                1

#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* native */
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                66
#define MOD_1_2_THRESHOLD                66
#define MOD_1_3_THRESHOLD               103
#define DIVREM_HENSEL_QR_1_THRESHOLD      6
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      4
#define DIVREM_EUCLID_HENSEL_THRESHOLD      9

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD             23
#define GET_STR_PRECOMPUTE_THRESHOLD     36
#define SET_STR_THRESHOLD              3987

#define MUL_FFT_TABLE  { 368, 992, 1408, 3584, 10240, 40960, 163840, 655360, 0 }
#define MUL_FFT_MODF_THRESHOLD          344
#define MUL_FFT_THRESHOLD              5632

#define SQR_FFT_TABLE  { 368, 928, 1408, 3584, 10240, 40960, 163840, 655360, 0 }
#define SQR_FFT_MODF_THRESHOLD          296
#define SQR_FFT_THRESHOLD              4608

/* Tuneup completed successfully, took 58 seconds */
