/* Generated by tuneup.c, 2009-06-02, gcc 4.1 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD              98
#define MUL_TOOM4_THRESHOLD             190
#define MUL_TOOM7_THRESHOLD             318

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD             113
#define SQR_TOOM4_THRESHOLD             184
#define SQR_TOOM7_THRESHOLD             242

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              40
#define MULLOW_MUL_N_THRESHOLD          342

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 56
#define POWM_THRESHOLD                   63

#define GCD_ACCEL_THRESHOLD              37
#define GCDEXT_THRESHOLD                 40
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               0
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD            MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD              6
#define GET_STR_PRECOMPUTE_THRESHOLD     10
#define SET_STR_THRESHOLD              3625

#define MUL_FFT_TABLE  { 272, 608, 1600, 2304, 7168, 20480, 81920, 196608, 0 }
#define MUL_FFT_MODF_THRESHOLD          216
#define MUL_FFT_THRESHOLD              3200

#define SQR_FFT_TABLE  { 240, 608, 1600, 2304, 5120, 20480, 81920, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          232
#define SQR_FFT_THRESHOLD              1664

/* Tuneup completed successfully, took 130 seconds */

