@echo off
rem %1 = directory holding config data (in cdata)

echo /* generated by gen_config_h.bat */ >tmp.h
for /f  %%a in (%1cfg.h) do (if "%%a" NEQ "" (echo #define HAVE_NATIVE_%%a 1 >>tmp.h))

type cfg.h >>tmp.h
call out_copy_rename tmp.h ..\ config.h
del tmp.h
