/* Generated by tuneup.c, 2011-12-04, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD             101
#define MUL_TOOM4_THRESHOLD             151
#define MUL_TOOM8H_THRESHOLD            230

#define SQR_BASECASE_THRESHOLD           11
#define SQR_KARATSUBA_THRESHOLD          47
#define SQR_TOOM3_THRESHOLD             136
#define SQR_TOOM4_THRESHOLD             136
#define SQR_TOOM8_THRESHOLD             230

#define POWM_THRESHOLD                  984

#define HGCD_THRESHOLD                   81
#define GCD_DC_THRESHOLD                890
#define GCDEXT_DC_THRESHOLD             978
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                 7
#define MOD_1_2_THRESHOLD                 7
#define MOD_1_3_THRESHOLD                 7
#define DIVREM_HENSEL_QR_1_THRESHOLD      2
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD      8

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             11
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           6915
#define SET_STR_PRECOMPUTE_THRESHOLD  19321

#define MUL_FFT_FULL_THRESHOLD         1856

#define SQR_FFT_FULL_THRESHOLD         1728

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              58
#define MULLOW_MUL_THRESHOLD           2743

#define MULHIGH_BASECASE_THRESHOLD        3
#define MULHIGH_DC_THRESHOLD             59
#define MULHIGH_MUL_THRESHOLD          2743

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD              28222
#define DC_DIV_QR_THRESHOLD              17
#define DC_DIVAPPR_Q_N_THRESHOLD         48
#define INV_DIV_QR_THRESHOLD           2350
#define INV_DIVAPPR_Q_N_THRESHOLD        48
#define DC_DIV_Q_THRESHOLD               95
#define INV_DIV_Q_THRESHOLD            2350
#define DC_DIVAPPR_Q_THRESHOLD           65
#define INV_DIVAPPR_Q_THRESHOLD        5363
#define DC_BDIV_QR_THRESHOLD             76
#define DC_BDIV_Q_THRESHOLD              22
/* Tuneup completed successfully, took 391 seconds */
