/* Generated by tuneup.c, 2010-03-24, gcc 4.0 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD              62
#define MUL_TOOM4_THRESHOLD             168
#define MUL_TOOM8H_THRESHOLD            173

#define SQR_BASECASE_THRESHOLD            0  /* always */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD              93
#define SQR_TOOM4_THRESHOLD             278
#define SQR_TOOM8_THRESHOLD             278

#define POWM_THRESHOLD                  984

#define GCD_ACCEL_THRESHOLD              64
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                 8
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                25
#define DIVREM_HENSEL_QR_1_THRESHOLD     31
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD     60
#define DIVREM_EUCLID_HENSEL_THRESHOLD     60

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             12
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD          17888
#define SET_STR_PRECOMPUTE_THRESHOLD  83721

#define MUL_FFT_TABLE  { 272, 672, 1600, 2304, 7168, 20480, 81920, 458752, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          272
#define MUL_FFT_FULL_THRESHOLD         1728

#define SQR_FFT_TABLE  { 272, 672, 1600, 2304, 7168, 20480, 81920, 327680, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          216
#define SQR_FFT_FULL_THRESHOLD         1728

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              47
#define MULLOW_MUL_THRESHOLD           3114

#define MULHIGH_BASECASE_THRESHOLD        5
#define MULHIGH_DC_THRESHOLD             45
#define MULHIGH_MUL_THRESHOLD          3207

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD              30861
#define DC_DIV_QR_THRESHOLD              20
#define DC_DIVAPPR_Q_N_THRESHOLD         54
#define INV_DIV_QR_THRESHOLD           3031
#define INV_DIVAPPR_Q_N_THRESHOLD        54
#define DC_DIV_Q_THRESHOLD               87
#define INV_DIV_Q_THRESHOLD            2397
#define DC_DIVAPPR_Q_THRESHOLD           72
#define INV_DIVAPPR_Q_THRESHOLD        6514
#define DC_BDIV_QR_THRESHOLD             48
#define DC_BDIV_Q_THRESHOLD              20
/* Tuneup completed successfully, took 1012 seconds */
