/* Generated by tuneup.c, 2012-10-24, gcc 4.7 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD             105
#define MUL_TOOM4_THRESHOLD             246

#define MUL_TOOM8H_THRESHOLD            327

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          31
#define SQR_TOOM3_THRESHOLD              61
#define SQR_TOOM4_THRESHOLD             178
#define SQR_TOOM8_THRESHOLD             240

#define POWM_THRESHOLD                  138

#define HGCD_THRESHOLD                   42
#define GCD_DC_THRESHOLD               2770

#define GCDEXT_DC_THRESHOLD            1788
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 7
#define MOD_1_2_THRESHOLD                 7
#define MOD_1_3_THRESHOLD                23
#define DIVREM_HENSEL_QR_1_THRESHOLD     31
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      5
#define DIVREM_EUCLID_HENSEL_THRESHOLD     15

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             16

#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           6915
#define SET_STR_PRECOMPUTE_THRESHOLD   6915


#define MUL_FFT_FULL_THRESHOLD         3008

#define SQR_FFT_FULL_THRESHOLD         3520

#define MULLOW_BASECASE_THRESHOLD         7
#define MULLOW_DC_THRESHOLD              30
#define MULLOW_MUL_THRESHOLD           4570


#define MULHIGH_BASECASE_THRESHOLD       10
#define MULHIGH_DC_THRESHOLD             27
#define MULHIGH_MUL_THRESHOLD          2966

#define MULMOD_2EXPM1_THRESHOLD          20

#define FAC_UI_THRESHOLD               1605
#define DC_DIV_QR_THRESHOLD             100
#define DC_DIVAPPR_Q_N_THRESHOLD         91
#define INV_DIV_QR_THRESHOLD            465
#define INV_DIVAPPR_Q_N_THRESHOLD        91
#define DC_DIV_Q_THRESHOLD              130
#define INV_DIV_Q_THRESHOLD            5581
#define DC_DIVAPPR_Q_THRESHOLD          102
#define INV_DIVAPPR_Q_THRESHOLD       12637
#define DC_BDIV_QR_THRESHOLD            100
#define DC_BDIV_Q_THRESHOLD              42


/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 3, 3 }, { 3, 2 }, { 2, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 3, 4, 4, 4, 3, 3, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1 }

#define FFT_N_NUM 23

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 137 seconds */