/* Generated by tuneup.c, 2011-06-05, gcc 4.5 */

#define MUL_KARATSUBA_THRESHOLD          18
#define MUL_TOOM3_THRESHOLD             100
#define MUL_TOOM4_THRESHOLD             169
#define MUL_TOOM8H_THRESHOLD            327

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          26
#define SQR_TOOM3_THRESHOLD              93
#define SQR_TOOM4_THRESHOLD             244
#define SQR_TOOM8_THRESHOLD             246

#define POWM_THRESHOLD                  138

#define GCD_THRESHOLD                   718
#define GCDEXT_THRESHOLD                842
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 7
#define MOD_1_2_THRESHOLD                 7
#define MOD_1_3_THRESHOLD                19
#define DIVREM_HENSEL_QR_1_THRESHOLD     36
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      5
#define DIVREM_EUCLID_HENSEL_THRESHOLD     35

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             14
#define GET_STR_PRECOMPUTE_THRESHOLD     22
#define SET_STR_DC_THRESHOLD          21598
#define SET_STR_PRECOMPUTE_THRESHOLD  21598

#define MUL_FFT_TABLE  { 336, 736, 1856, 2304, 7168, 20480, 81920, 327680, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          296
#define MUL_FFT_FULL_THRESHOLD         1952

#define SQR_FFT_TABLE  { 336, 736, 1728, 2304, 7168, 20480, 81920, 327680, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          248
#define SQR_FFT_FULL_THRESHOLD         1824

#define MULLOW_BASECASE_THRESHOLD         6
#define MULLOW_DC_THRESHOLD              26
#define MULLOW_MUL_THRESHOLD           3207

#define MULHIGH_BASECASE_THRESHOLD       10
#define MULHIGH_DC_THRESHOLD             27
#define MULHIGH_MUL_THRESHOLD          3207

#define MULMOD_2EXPM1_THRESHOLD          18

#define FAC_UI_THRESHOLD              15869
#define DC_DIV_QR_THRESHOLD              38
#define DC_DIVAPPR_Q_N_THRESHOLD         90
#define INV_DIV_QR_THRESHOLD           3215
#define INV_DIVAPPR_Q_N_THRESHOLD        90
#define DC_DIV_Q_THRESHOLD              132
#define INV_DIV_Q_THRESHOLD            4234
#define DC_DIVAPPR_Q_THRESHOLD          104
#define INV_DIVAPPR_Q_THRESHOLD        8751
#define DC_BDIV_QR_THRESHOLD             29
#define DC_BDIV_Q_THRESHOLD              44
/* Tuneup completed successfully, took 326 seconds */
