/* Generated by tuneup.c, 2012-10-17, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          21
#define MUL_TOOM3_THRESHOLD             127
#define MUL_TOOM4_THRESHOLD             360
#define MUL_TOOM8H_THRESHOLD            414

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          41
#define SQR_TOOM3_THRESHOLD             121
#define SQR_TOOM4_THRESHOLD             522
#define SQR_TOOM8_THRESHOLD             644

#define POWM_THRESHOLD                  349

#define HGCD_THRESHOLD                  177
#define GCD_DC_THRESHOLD               2995
#define GCDEXT_DC_THRESHOLD            2213
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 4
#define MOD_1_2_THRESHOLD                10
#define MOD_1_3_THRESHOLD                29
#define DIVREM_HENSEL_QR_1_THRESHOLD      6
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      6
#define DIVREM_EUCLID_HENSEL_THRESHOLD     29

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             19
#define GET_STR_PRECOMPUTE_THRESHOLD     25
#define SET_STR_DC_THRESHOLD           7863
#define SET_STR_PRECOMPUTE_THRESHOLD   8180

#define MUL_FFT_FULL_THRESHOLD         7232

#define SQR_FFT_FULL_THRESHOLD         7232

#define MULLOW_BASECASE_THRESHOLD         9
#define MULLOW_DC_THRESHOLD              29
#define MULLOW_MUL_THRESHOLD           9970

#define MULHIGH_BASECASE_THRESHOLD       13
#define MULHIGH_DC_THRESHOLD             34
#define MULHIGH_MUL_THRESHOLD          4481

#define MULMOD_2EXPM1_THRESHOLD          16

#define FAC_UI_THRESHOLD               1024
#define DC_DIV_QR_THRESHOLD             298
#define DC_DIVAPPR_Q_N_THRESHOLD        134
#define INV_DIV_QR_THRESHOLD            807
#define INV_DIVAPPR_Q_N_THRESHOLD       134
#define DC_DIV_Q_THRESHOLD              186
#define INV_DIV_Q_THRESHOLD            7356
#define DC_DIVAPPR_Q_THRESHOLD          162
#define INV_DIVAPPR_Q_THRESHOLD       18500
#define DC_BDIV_QR_THRESHOLD            278
#define DC_BDIV_Q_THRESHOLD              33

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 4, 3 }, { 3, 2 }, { 2, 1 }, { 2, 1 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1 }

#define FFT_N_NUM 23

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 192 seconds */

