# $Id: Makefile.inc 2367 2010-09-06 19:33:25Z peter $

TESTS += modules/dbgfmts/dwarf2/tests/gen64/dwarf2_gen64_test.sh

EXTRA_DIST += modules/dbgfmts/dwarf2/tests/gen64/dwarf2_gen64_test.sh
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/gen64/dwarf64_pathname.asm
EXTRA_DIST += modules/dbgfmts/dwarf2/tests/gen64/dwarf64_pathname.hex

