/* Generated by tuneup.c, 2012-10-24, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          10
#define MUL_TOOM3_THRESHOLD              66
#define MUL_TOOM4_THRESHOLD             171
#define MUL_TOOM8H_THRESHOLD            222

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          19
#define SQR_TOOM3_THRESHOLD             113
#define SQR_TOOM4_THRESHOLD             298
#define SQR_TOOM8_THRESHOLD             298

#define POWM_THRESHOLD                   53

#define HGCD_THRESHOLD                   87
#define GCD_DC_THRESHOLD               1432
#define GCDEXT_DC_THRESHOLD             951
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 7
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                11
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD    212

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             19
#define GET_STR_PRECOMPUTE_THRESHOLD     33
#define SET_STR_DC_THRESHOLD           3904
#define SET_STR_PRECOMPUTE_THRESHOLD  20906

#define MUL_FFT_FULL_THRESHOLD         2016

#define SQR_FFT_FULL_THRESHOLD         2368

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              10
#define MULLOW_MUL_THRESHOLD           2347

#define MULHIGH_BASECASE_THRESHOLD        8
#define MULHIGH_DC_THRESHOLD              8
#define MULHIGH_MUL_THRESHOLD          2393

#define MULMOD_2EXPM1_THRESHOLD          14

#define FAC_UI_THRESHOLD               2127
#define DC_DIV_QR_THRESHOLD             100
#define DC_DIVAPPR_Q_N_THRESHOLD         74
#define INV_DIV_QR_THRESHOLD            465
#define INV_DIVAPPR_Q_N_THRESHOLD        74
#define DC_DIV_Q_THRESHOLD              108
#define INV_DIV_Q_THRESHOLD            2914
#define DC_DIVAPPR_Q_THRESHOLD           81
#define INV_DIVAPPR_Q_THRESHOLD        6079
#define DC_BDIV_QR_THRESHOLD            100
#define DC_BDIV_Q_THRESHOLD              36

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 3, 2 }, { 2, 2 }, { 2, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 3, 3, 4, 4, 3, 3, 3, 3, 2, 2, 3, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 19

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 786 seconds */
