/* Generated by tuneup.c, 2011-02-22, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          10
#define MUL_TOOM3_THRESHOLD              65
#define MUL_TOOM4_THRESHOLD             169
#define MUL_TOOM8H_THRESHOLD            206

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          16
#define SQR_TOOM3_THRESHOLD              90
#define SQR_TOOM4_THRESHOLD             278
#define SQR_TOOM8_THRESHOLD             278

#define POWM_THRESHOLD                   55

#define GCD_THRESHOLD                   704
#define GCDEXT_THRESHOLD                490
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                13
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD     15

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             16
#define GET_STR_PRECOMPUTE_THRESHOLD     30
#define SET_STR_DC_THRESHOLD            214
#define SET_STR_PRECOMPUTE_THRESHOLD    275

#define MUL_FFT_TABLE  { 272, 544, 1344, 1792, 5120, 20480, 49152, 327680, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          288
#define MUL_FFT_FULL_THRESHOLD         1472

#define SQR_FFT_TABLE  { 240, 544, 1344, 1792, 5120, 20480, 81920, 196608, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          184
#define SQR_FFT_FULL_THRESHOLD         1472

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              10
#define MULLOW_MUL_THRESHOLD           2171

#define MULHIGH_BASECASE_THRESHOLD        8
#define MULHIGH_DC_THRESHOLD              8
#define MULHIGH_MUL_THRESHOLD          2171

#define MULMOD_2EXPM1_THRESHOLD          12

#define FAC_UI_THRESHOLD               8252
#define DC_DIV_QR_THRESHOLD              31
#define DC_DIVAPPR_Q_N_THRESHOLD         74
#define INV_DIV_QR_THRESHOLD           1142
#define INV_DIVAPPR_Q_N_THRESHOLD        74
#define DC_DIV_Q_THRESHOLD              108
#define INV_DIV_Q_THRESHOLD            2009
#define DC_DIVAPPR_Q_THRESHOLD           81
#define INV_DIVAPPR_Q_THRESHOLD        4569
#define DC_BDIV_QR_THRESHOLD             28
#define DC_BDIV_Q_THRESHOLD              34
/* Tuneup completed successfully, took 1568 seconds */
