# $Id: Makefile.inc 1777 2007-02-19 08:21:17Z peter $

TESTS += modules/objfmts/macho/tests/nasm64/macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.c
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho-reloc64-err.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho-reloc64-err.errwarn
