# $Id: Makefile.inc 2365 2010-08-18 06:23:30Z peter $

TESTS += modules/objfmts/win32/tests/gas/win32_gas_test.sh

EXTRA_DIST += modules/objfmts/win32/tests/gas/win32_gas_test.sh
EXTRA_DIST += modules/objfmts/win32/tests/gas/win32at.asm
EXTRA_DIST += modules/objfmts/win32/tests/gas/win32at.hex
EXTRA_DIST += modules/objfmts/win32/tests/gas/win32def.asm
EXTRA_DIST += modules/objfmts/win32/tests/gas/win32def.hex
EXTRA_DIST += modules/objfmts/win32/tests/gas/win32secrel32.asm
EXTRA_DIST += modules/objfmts/win32/tests/gas/win32secrel32.hex
