/* Generated by tuneup.c, 2011-12-03, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          42
#define MUL_TOOM3_THRESHOLD              55
#define MUL_TOOM4_THRESHOLD              86
#define MUL_TOOM8H_THRESHOLD            182

#define SQR_BASECASE_THRESHOLD            7
#define SQR_KARATSUBA_THRESHOLD          83
#define SQR_TOOM3_THRESHOLD             109
#define SQR_TOOM4_THRESHOLD             194
#define SQR_TOOM8_THRESHOLD             262

#define POWM_THRESHOLD                   28

#define HGCD_THRESHOLD                   44
#define GCD_DC_THRESHOLD               1264
#define GCDEXT_DC_THRESHOLD             842
#define JACOBI_BASE_METHOD                2

#define DIVREM_1_NORM_THRESHOLD           7
#define DIVREM_1_UNNORM_THRESHOLD        14
#define MOD_1_NORM_THRESHOLD              8
#define MOD_1_UNNORM_THRESHOLD           14
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                8
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                 7
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                17
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD      9

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD              9
#define GET_STR_PRECOMPUTE_THRESHOLD     18
#define SET_STR_DC_THRESHOLD            262
#define SET_STR_PRECOMPUTE_THRESHOLD    835

#define MUL_FFT_TABLE  { 208, 608, 1152, 3584, 14336, 40960, 163840, 655360, 1572864, 10485760, 0 }
#define MUL_FFT_MODF_THRESHOLD          168
#define MUL_FFT_FULL_THRESHOLD         1408

#define SQR_FFT_TABLE  { 336, 800, 1152, 3584, 10240, 24576, 98304, 655360, 2621440, 10485760, 0 }
#define SQR_FFT_MODF_THRESHOLD          168
#define SQR_FFT_FULL_THRESHOLD         1408

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD             157
#define MULLOW_MUL_THRESHOLD           2464

#define MULHIGH_BASECASE_THRESHOLD        3
#define MULHIGH_DC_THRESHOLD            159
#define MULHIGH_MUL_THRESHOLD          2852

#define MULMOD_2EXPM1_THRESHOLD          18

#define FAC_UI_THRESHOLD               2877
#define DC_DIV_QR_THRESHOLD             114
#define DC_DIVAPPR_Q_N_THRESHOLD        283
#define INV_DIV_QR_THRESHOLD           2397
#define INV_DIVAPPR_Q_N_THRESHOLD       283
#define DC_DIV_Q_THRESHOLD              456
#define INV_DIV_Q_THRESHOLD            3547
#define DC_DIVAPPR_Q_THRESHOLD          263
#define INV_DIVAPPR_Q_THRESHOLD        9670
#define DC_BDIV_QR_THRESHOLD             99
#define DC_BDIV_Q_THRESHOLD             372
/* Tuneup completed successfully, took 2637 seconds */
