/* Generated by tuneup.c, 2009-10-08, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          10
#define MUL_TOOM3_THRESHOLD              66
#define MUL_TOOM4_THRESHOLD             190
#define MUL_TOOM7_THRESHOLD             321

#define SQR_BASECASE_THRESHOLD            6
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD             177
#define SQR_TOOM4_THRESHOLD             345
#define SQR_TOOM7_THRESHOLD             434

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              35
#define MULLOW_MUL_THRESHOLD           9970

#define MULHIGH_BASECASE_THRESHOLD        0  /* always */
#define MULHIGH_DC_THRESHOLD             34
#define MULHIGH_MUL_THRESHOLD          9970

#define MULMOD_2EXPM1_THRESHOLD          10

#define DIV_SB_PREINV_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIV_DC_THRESHOLD                 40
#define POWM_THRESHOLD                   46
#define FAC_UI_THRESHOLD               1486

#define GCD_ACCEL_THRESHOLD              28
#define GCDEXT_THRESHOLD                  9
#define JACOBI_BASE_METHOD                2

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD          MP_SIZE_T_MAX  /* never */
#define MOD_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  0
#define DIVREM_2_THRESHOLD            MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                22
#define MOD_1_2_THRESHOLD                22
#define MOD_1_3_THRESHOLD                22
#define DIVREM_HENSEL_QR_1_THRESHOLD     25
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD     25
#define DIVREM_EUCLID_HENSEL_THRESHOLD      9

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             11
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_THRESHOLD              1694

#define MUL_FFT_TABLE  { 208, 544, 896, 2560, 6144, 40960, 0 }
#define MUL_FFT_MODF_THRESHOLD          184
#define MUL_FFT_THRESHOLD              1792

#define SQR_FFT_TABLE  { 240, 480, 896, 2560, 6144, 24576, 0 }
#define SQR_FFT_MODF_THRESHOLD          232
#define SQR_FFT_THRESHOLD              1216

/* Tuneup completed successfully, took 266 seconds */
