/* Generated by tuneup.c, 2012-10-23, gcc 4.7 */

#define MUL_KARATSUBA_THRESHOLD          27
#define MUL_TOOM3_THRESHOLD              73
#define MUL_TOOM4_THRESHOLD              84
#define MUL_TOOM8H_THRESHOLD            194

#define SQR_BASECASE_THRESHOLD            4  /* karatsuba */
#define SQR_KARATSUBA_THRESHOLD           0  /* never sqr_basecase */
#define SQR_TOOM3_THRESHOLD              94
#define SQR_TOOM4_THRESHOLD             154
#define SQR_TOOM8_THRESHOLD             189

#define POWM_THRESHOLD                   19

#define HGCD_THRESHOLD                   51
#define GCD_DC_THRESHOLD               1460
#define GCDEXT_DC_THRESHOLD             826
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD           4
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              8
#define MOD_1_UNNORM_THRESHOLD           13
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD               13
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */
#define MOD_1_1_THRESHOLD                 8
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                17
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD     16

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             10
#define GET_STR_PRECOMPUTE_THRESHOLD     18
#define SET_STR_DC_THRESHOLD            101
#define SET_STR_PRECOMPUTE_THRESHOLD    172

#define MUL_FFT_FULL_THRESHOLD         2880

#define SQR_FFT_FULL_THRESHOLD         1632

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              21
#define MULLOW_MUL_THRESHOLD            195

#define MULHIGH_BASECASE_THRESHOLD        0  /* always */
#define MULHIGH_DC_THRESHOLD             67
#define MULHIGH_MUL_THRESHOLD            94

#define MULMOD_2EXPM1_THRESHOLD          18

#define FAC_UI_THRESHOLD               1034
#define DC_DIV_QR_THRESHOLD              21
#define DC_DIVAPPR_Q_N_THRESHOLD         23
#define INV_DIV_QR_THRESHOLD            195
#define INV_DIVAPPR_Q_N_THRESHOLD        23
#define DC_DIV_Q_THRESHOLD              327
#define INV_DIV_Q_THRESHOLD            2541
#define DC_DIVAPPR_Q_THRESHOLD           81
#define INV_DIVAPPR_Q_THRESHOLD       14326
#define DC_BDIV_QR_THRESHOLD             84
#define DC_BDIV_Q_THRESHOLD              90

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 3, 2 }, { 3, 2 }, { 2, 1 }, { 1, 0 }, { 0, 0 } }

#define MULMOD_TAB \
   { 3, 2, 2, 3, 3, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 11

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 1831 seconds */
