/* Generated by tuneup.c, 2010-03-24, gcc 4.3 */

#define MUL_KARATSUBA_THRESHOLD          24
#define MUL_TOOM3_THRESHOLD              85
#define MUL_TOOM4_THRESHOLD             244
#define MUL_TOOM8H_THRESHOLD            466

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          32
#define SQR_TOOM3_THRESHOLD             104
#define SQR_TOOM4_THRESHOLD             486
#define SQR_TOOM8_THRESHOLD             562

#define POWM_THRESHOLD                  414

#define GCD_ACCEL_THRESHOLD              93
#define GCDEXT_THRESHOLD                  0  /* always */
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 4
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                24
#define DIVREM_HENSEL_QR_1_THRESHOLD      8
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      7
#define DIVREM_EUCLID_HENSEL_THRESHOLD    132

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD             15
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD            552
#define SET_STR_PRECOMPUTE_THRESHOLD  98335

#define MUL_FFT_TABLE  { 432, 928, 2880, 3328, 7168, 36864, 114688, 458752, 2359296, 9437184, 0 }
#define MUL_FFT_MODF_THRESHOLD          528
#define MUL_FFT_FULL_THRESHOLD         3008

#define SQR_FFT_TABLE  { 464, 992, 2368, 2816, 11264, 36864, 114688, 458752, 2359296, 7340032, 0 }
#define SQR_FFT_MODF_THRESHOLD          464
#define SQR_FFT_FULL_THRESHOLD         2496

#define MULLOW_BASECASE_THRESHOLD        11
#define MULLOW_DC_THRESHOLD              12
#define MULLOW_MUL_THRESHOLD           9970

#define MULHIGH_BASECASE_THRESHOLD       22
#define MULHIGH_DC_THRESHOLD             22
#define MULHIGH_MUL_THRESHOLD          9970

#define MULMOD_2EXPM1_THRESHOLD          20

#define FAC_UI_THRESHOLD              32756
#define DC_DIV_QR_THRESHOLD              45
#define DC_DIVAPPR_Q_N_THRESHOLD        180
#define INV_DIV_QR_THRESHOLD           9894
#define INV_DIVAPPR_Q_N_THRESHOLD       180
#define DC_DIV_Q_THRESHOLD              217
#define INV_DIV_Q_THRESHOLD            9894
#define DC_DIVAPPR_Q_THRESHOLD          201
#define INV_DIVAPPR_Q_THRESHOLD       19066
#define DC_BDIV_QR_THRESHOLD             42
#define DC_BDIV_Q_THRESHOLD              20
/* Tuneup completed successfully, took 756 seconds */
