/* Generated by tuneup.c, 2017-01-30, gcc 4.8 */

#define MUL_KARATSUBA_THRESHOLD          21
#define MUL_TOOM3_THRESHOLD             137
#define MUL_TOOM4_THRESHOLD             195
#define MUL_TOOM8H_THRESHOLD            399

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          32
#define SQR_TOOM3_THRESHOLD              97
#define SQR_TOOM4_THRESHOLD             266
#define SQR_TOOM8_THRESHOLD             512

#define POWM_THRESHOLD                   32

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                13
#define DIVREM_HENSEL_QR_1_THRESHOLD     29
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      6
#define DIVREM_EUCLID_HENSEL_THRESHOLD     14

#define MUL_FFT_FULL_THRESHOLD         7104

#define SQR_FFT_FULL_THRESHOLD         3904

#define MULLOW_BASECASE_THRESHOLD         7
#define MULLOW_DC_THRESHOLD              62
#define MULLOW_MUL_THRESHOLD           3504

#define MULHIGH_BASECASE_THRESHOLD        9
#define MULHIGH_DC_THRESHOLD             62
#define MULHIGH_MUL_THRESHOLD          3504

#define MULMOD_2EXPM1_THRESHOLD          18

#define DC_DIV_QR_THRESHOLD              35
#define INV_DIV_QR_THRESHOLD           2444
#define INV_DIVAPPR_Q_N_THRESHOLD        35
#define DC_DIV_Q_THRESHOLD               45
#define INV_DIV_Q_THRESHOLD            1308
#define DC_DIVAPPR_Q_THRESHOLD          142
#define INV_DIVAPPR_Q_THRESHOLD       13280
#define DC_BDIV_QR_THRESHOLD             64
#define DC_BDIV_Q_THRESHOLD             144

#define ROOTREM_THRESHOLD                 6

#define MATRIX22_STRASSEN_THRESHOLD      15
#define HGCD_THRESHOLD                  106
#define HGCD_APPR_THRESHOLD              91
#define HGCD_REDUCE_THRESHOLD          6852
#define GCD_DC_THRESHOLD                706
#define GCDEXT_DC_THRESHOLD             492
#define JACOBI_BASE_METHOD                2

#define GET_STR_DC_THRESHOLD             14
#define GET_STR_PRECOMPUTE_THRESHOLD     20
#define SET_STR_DC_THRESHOLD           2393
#define SET_STR_PRECOMPUTE_THRESHOLD   4064

#define FAC_DSC_THRESHOLD               858
#define FAC_ODD_THRESHOLD                45

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 4 }, { 4, 3 }, { 3, 2 }, { 3, 2 }, { 2, 1 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 19

#define FFT_MULMOD_2EXPP1_CUTOFF 256


/* Tuneup completed successfully, took 64 seconds */
