copy e:\Working\mpir\build.vc12\dll_mpir_core2\dll_mpir_core2.vcxproj.filters e:\Working\mpir\build.vc12\dll_mpir_core2\dll_mpir_core2_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\dll_mpir_gc\dll_mpir_gc.vcxproj.filters e:\Working\mpir\build.vc12\dll_mpir_gc\dll_mpir_gc_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\dll_mpir_k8\dll_mpir_k8.vcxproj.filters e:\Working\mpir\build.vc12\dll_mpir_k8\dll_mpir_k8_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\dll_mpir_nehalem\dll_mpir_nehalem.vcxproj.filters e:\Working\mpir\build.vc12\dll_mpir_nehalem\dll_mpir_nehalem_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\dll_mpir_p3\dll_mpir_p3.vcxproj.filters e:\Working\mpir\build.vc12\dll_mpir_p3\dll_mpir_p3_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\dll_mpir_sandybridge\dll_mpir_sandybridge.vcxproj.filters e:\Working\mpir\build.vc12\dll_mpir_sandybridge\dll_mpir_sandybridge_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_core2\lib_mpir_core2.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_core2\lib_mpir_core2_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_cxx\lib_mpir_cxx.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_cxx\lib_mpir_cxx_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_gc\lib_mpir_gc.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_gc\lib_mpir_gc_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_k8\lib_mpir_k8.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_k8\lib_mpir_k8_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_nehalem\lib_mpir_nehalem.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_nehalem\lib_mpir_nehalem_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_p3\lib_mpir_p3.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_p3\lib_mpir_p3_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_mpir_sandybridge\lib_mpir_sandybridge.vcxproj.filters e:\Working\mpir\build.vc12\lib_mpir_sandybridge\lib_mpir_sandybridge_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\lib_speed\lib_speed.vcxproj.filters e:\Working\mpir\build.vc12\lib_speed\lib_speed_p.vcxproj.filters
copy e:\Working\mpir\build.vc12\dll_mpir_core2\dll_mpir_core2.vcxproj e:\Working\mpir\build.vc12\dll_mpir_core2\dll_mpir_core2_p.vcxproj
copy e:\Working\mpir\build.vc12\dll_mpir_gc\dll_mpir_gc.vcxproj e:\Working\mpir\build.vc12\dll_mpir_gc\dll_mpir_gc_p.vcxproj
copy e:\Working\mpir\build.vc12\dll_mpir_k8\dll_mpir_k8.vcxproj e:\Working\mpir\build.vc12\dll_mpir_k8\dll_mpir_k8_p.vcxproj
copy e:\Working\mpir\build.vc12\dll_mpir_nehalem\dll_mpir_nehalem.vcxproj e:\Working\mpir\build.vc12\dll_mpir_nehalem\dll_mpir_nehalem_p.vcxproj
copy e:\Working\mpir\build.vc12\dll_mpir_p3\dll_mpir_p3.vcxproj e:\Working\mpir\build.vc12\dll_mpir_p3\dll_mpir_p3_p.vcxproj
copy e:\Working\mpir\build.vc12\dll_mpir_sandybridge\dll_mpir_sandybridge.vcxproj e:\Working\mpir\build.vc12\dll_mpir_sandybridge\dll_mpir_sandybridge_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_core2\lib_mpir_core2.vcxproj e:\Working\mpir\build.vc12\lib_mpir_core2\lib_mpir_core2_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_cxx\lib_mpir_cxx.vcxproj e:\Working\mpir\build.vc12\lib_mpir_cxx\lib_mpir_cxx_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_gc\lib_mpir_gc.vcxproj e:\Working\mpir\build.vc12\lib_mpir_gc\lib_mpir_gc_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_k8\lib_mpir_k8.vcxproj e:\Working\mpir\build.vc12\lib_mpir_k8\lib_mpir_k8_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_nehalem\lib_mpir_nehalem.vcxproj e:\Working\mpir\build.vc12\lib_mpir_nehalem\lib_mpir_nehalem_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_p3\lib_mpir_p3.vcxproj e:\Working\mpir\build.vc12\lib_mpir_p3\lib_mpir_p3_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_mpir_sandybridge\lib_mpir_sandybridge.vcxproj e:\Working\mpir\build.vc12\lib_mpir_sandybridge\lib_mpir_sandybridge_p.vcxproj
copy e:\Working\mpir\build.vc12\lib_speed\lib_speed.vcxproj e:\Working\mpir\build.vc12\lib_speed\lib_speed_p.vcxproj