/* Generated by tuneup.c, 2011-11-15, gcc 4.5 */

#define MUL_KARATSUBA_THRESHOLD          22
#define MUL_TOOM3_THRESHOLD             134
#define MUL_TOOM4_THRESHOLD             242
#define MUL_TOOM8H_THRESHOLD            414

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          43
#define SQR_TOOM3_THRESHOLD             124
#define SQR_TOOM4_THRESHOLD             512
#define SQR_TOOM8_THRESHOLD             674

#define POWM_THRESHOLD                  391

#define HGCD_THRESHOLD                   30
#define GCD_DC_THRESHOLD               2048
#define GCDEXT_DC_THRESHOLD            1252
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 4
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                11
#define DIVREM_HENSEL_QR_1_THRESHOLD      8
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      7
#define DIVREM_EUCLID_HENSEL_THRESHOLD     21

#define ROOTREM_THRESHOLD                 8

#define GET_STR_DC_THRESHOLD             16
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           8262
#define SET_STR_PRECOMPUTE_THRESHOLD  55160

#define MUL_FFT_FULL_THRESHOLD         3008

#define SQR_FFT_FULL_THRESHOLD         2496

#define MULLOW_BASECASE_THRESHOLD         9
#define MULLOW_DC_THRESHOLD              17
#define MULLOW_MUL_THRESHOLD           9970

#define MULHIGH_BASECASE_THRESHOLD       25
#define MULHIGH_DC_THRESHOLD             25
#define MULHIGH_MUL_THRESHOLD          9970

#define MULMOD_2EXPM1_THRESHOLD          22

#define FAC_UI_THRESHOLD              32756
#define DC_DIV_QR_THRESHOLD              46
#define DC_DIVAPPR_Q_N_THRESHOLD        156
#define INV_DIV_QR_THRESHOLD           9894
#define INV_DIVAPPR_Q_N_THRESHOLD       156
#define DC_DIV_Q_THRESHOLD              192
#define INV_DIV_Q_THRESHOLD            9894
#define DC_DIVAPPR_Q_THRESHOLD          171
#define INV_DIVAPPR_Q_THRESHOLD       19441
#define DC_BDIV_QR_THRESHOLD             42
#define DC_BDIV_Q_THRESHOLD              20
/* Tuneup completed successfully, took 817 seconds */
