/* Generated by tuneup.c, 2012-10-23, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          24
#define MUL_TOOM3_THRESHOLD             137
#define MUL_TOOM4_THRESHOLD             236
#define MUL_TOOM8H_THRESHOLD            430

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          47
#define SQR_TOOM3_THRESHOLD             137
#define SQR_TOOM4_THRESHOLD             375
#define SQR_TOOM8_THRESHOLD             739

#define POWM_THRESHOLD                  426

#define HGCD_THRESHOLD                   30
#define GCD_DC_THRESHOLD               2995
#define GCDEXT_DC_THRESHOLD            1913
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 4
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                24
#define DIVREM_HENSEL_QR_1_THRESHOLD      7
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      7
#define DIVREM_EUCLID_HENSEL_THRESHOLD     23

#define ROOTREM_THRESHOLD                 7

#define GET_STR_DC_THRESHOLD             17
#define GET_STR_PRECOMPUTE_THRESHOLD     26
#define SET_STR_DC_THRESHOLD            537
#define SET_STR_PRECOMPUTE_THRESHOLD   3317

#define MUL_FFT_FULL_THRESHOLD         8000

#define SQR_FFT_FULL_THRESHOLD         6336

#define MULLOW_BASECASE_THRESHOLD        10
#define MULLOW_DC_THRESHOLD              17
#define MULLOW_MUL_THRESHOLD           4801

#define MULHIGH_BASECASE_THRESHOLD       19
#define MULHIGH_DC_THRESHOLD             19
#define MULHIGH_MUL_THRESHOLD          5402

#define MULMOD_2EXPM1_THRESHOLD          20

#define FAC_UI_THRESHOLD               5782
#define DC_DIV_QR_THRESHOLD             358
#define DC_DIVAPPR_Q_N_THRESHOLD        156
#define INV_DIV_QR_THRESHOLD            979
#define INV_DIVAPPR_Q_N_THRESHOLD       156
#define DC_DIV_Q_THRESHOLD              189
#define INV_DIV_Q_THRESHOLD            9894
#define DC_DIVAPPR_Q_THRESHOLD          171
#define INV_DIVAPPR_Q_THRESHOLD       19441
#define DC_BDIV_QR_THRESHOLD            358
#define DC_BDIV_Q_THRESHOLD              28

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 4 }, { 4, 3 }, { 3, 2 }, { 3, 2 }, { 2, 1 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 23

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 423 seconds */
