/* Generated by tuneup.c, 2014-02-21, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          18
#define MUL_TOOM3_THRESHOLD              65
#define MUL_TOOM4_THRESHOLD             148
#define MUL_TOOM8H_THRESHOLD            238

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          22
#define SQR_TOOM3_THRESHOLD              81
#define SQR_TOOM4_THRESHOLD             214
#define SQR_TOOM8_THRESHOLD             321

#define POWM_THRESHOLD                   83

#define HGCD_THRESHOLD                   33
#define GCD_DC_THRESHOLD                486
#define GCDEXT_DC_THRESHOLD             357
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                17
#define DIVREM_HENSEL_QR_1_THRESHOLD      8
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      4
#define DIVREM_EUCLID_HENSEL_THRESHOLD     58

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             12
#define GET_STR_PRECOMPUTE_THRESHOLD     16
#define SET_STR_DC_THRESHOLD            668
#define SET_STR_PRECOMPUTE_THRESHOLD   1260

#define MUL_FFT_FULL_THRESHOLD         3904

#define SQR_FFT_FULL_THRESHOLD         2752

#define MULLOW_BASECASE_THRESHOLD         4
#define MULLOW_DC_THRESHOLD              16
#define MULLOW_MUL_THRESHOLD           4994

#define MULHIGH_BASECASE_THRESHOLD        9
#define MULHIGH_DC_THRESHOLD             15
#define MULHIGH_MUL_THRESHOLD          2324

#define MULMOD_2EXPM1_THRESHOLD          12

#define FAC_UI_THRESHOLD              11784
#define DC_DIV_QR_THRESHOLD              54
#define DC_DIVAPPR_Q_N_THRESHOLD         45
#define INV_DIV_QR_THRESHOLD           1528
#define INV_DIVAPPR_Q_N_THRESHOLD        45
#define DC_DIV_Q_THRESHOLD              140
#define INV_DIV_Q_THRESHOLD            3991
#define DC_DIVAPPR_Q_THRESHOLD           29
#define INV_DIVAPPR_Q_THRESHOLD       14326
#define DC_BDIV_QR_THRESHOLD             51
#define DC_BDIV_Q_THRESHOLD              96

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   { { 4, 3 }, { 3, 3 }, { 3, 2 }, { 2, 1 }, { 1, 0 } }

#define MULMOD_TAB \
   { 4, 4, 3, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 19

#define FFT_MULMOD_2EXPP1_CUTOFF 128


/* Tuneup completed successfully, took 139 seconds */

