/* Generated by tuneup.c, 2014-03-21, system compiler */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD             116
#define MUL_TOOM4_THRESHOLD             180
#define MUL_TOOM8H_THRESHOLD            242

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          30
#define SQR_TOOM3_THRESHOLD             170
#define SQR_TOOM4_THRESHOLD             360
#define SQR_TOOM8_THRESHOLD             360

#define POWM_THRESHOLD                  984

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              4
#define MOD_1_UNNORM_THRESHOLD            3
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                72
#define MOD_1_2_THRESHOLD                86
#define MOD_1_3_THRESHOLD               190
#define DIVREM_HENSEL_QR_1_THRESHOLD      5
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD     11

#define MUL_FFT_FULL_THRESHOLD         7136

#define SQR_FFT_FULL_THRESHOLD         5088

#define MULLOW_BASECASE_THRESHOLD         4
#define MULLOW_DC_THRESHOLD              36
#define MULLOW_MUL_THRESHOLD           2716

#define MULHIGH_BASECASE_THRESHOLD       18
#define MULHIGH_DC_THRESHOLD             18
#define MULHIGH_MUL_THRESHOLD          2347

#define MULMOD_2EXPM1_THRESHOLD          30

#define SB_DIVAPPR_Q_SMALL_THRESHOLD     48
#define SB_DIV_QR_SMALL_THRESHOLD        39
#define DC_DIV_QR_THRESHOLD              22
#define INV_DIV_QR_THRESHOLD           2444
#define INV_DIVAPPR_Q_N_THRESHOLD        22
#define DC_DIV_Q_THRESHOLD              104
#define INV_DIV_Q_THRESHOLD            1652
#define DC_DIVAPPR_Q_THRESHOLD           33
#define INV_DIVAPPR_Q_THRESHOLD       18575
#define DC_BDIV_QR_THRESHOLD             46
#define DC_BDIV_Q_THRESHOLD              38

#define ROOTREM_THRESHOLD                12

#define MATRIX22_STRASSEN_THRESHOLD      23
#define HGCD_THRESHOLD                   95
#define HGCD_APPR_THRESHOLD              50
#define HGCD_REDUCE_THRESHOLD          6852
#define GCD_DC_THRESHOLD                521
#define GCDEXT_DC_THRESHOLD             365
#define JACOBI_BASE_METHOD                2

#define GET_STR_DC_THRESHOLD             23
#define GET_STR_PRECOMPUTE_THRESHOLD     40
#define SET_STR_DC_THRESHOLD           1045
#define SET_STR_PRECOMPUTE_THRESHOLD   2561

#define FAC_DSC_THRESHOLD               662
#define FAC_ODD_THRESHOLD                 0  /* always */

/* fft_tuning -- autogenerated by tune-fft */

#define FFT_TAB \
   {{ 4, 4 }, { 4, 3 }, { 3, 3 }, { 3, 2 }, { 2, 1 } }

#define MULMOD_TAB \
   { 4, 4, 4, 4, 4, 4, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 }

#define FFT_N_NUM 35

#define FFT_MULMOD_2EXPP1_CUTOFF 512
