/* Generated by tuneup.c, 2011-11-22, gcc 4.4 */

#define MUL_KARATSUBA_THRESHOLD          10
#define MUL_TOOM3_THRESHOLD              66
#define MUL_TOOM4_THRESHOLD             169
#define MUL_TOOM8H_THRESHOLD            222

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          19
#define SQR_TOOM3_THRESHOLD             113
#define SQR_TOOM4_THRESHOLD             298
#define SQR_TOOM8_THRESHOLD             298

#define POWM_THRESHOLD                   53

#define HGCD_THRESHOLD                   43
#define GCD_DC_THRESHOLD                680
#define GCDEXT_DC_THRESHOLD             438
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD       MP_SIZE_T_MAX  /* never */
#define DIVREM_1_UNNORM_THRESHOLD     MP_SIZE_T_MAX  /* never */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                13
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD     16

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             18
#define GET_STR_PRECOMPUTE_THRESHOLD     31
#define SET_STR_DC_THRESHOLD          17711
#define SET_STR_PRECOMPUTE_THRESHOLD  18794

#define MUL_FFT_TABLE  { 272, 544, 1344, 1792, 5120, 20480, 49152, 327680, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          288
#define MUL_FFT_FULL_THRESHOLD         1472

#define SQR_FFT_TABLE  { 240, 544, 1344, 1792, 5120, 20480, 81920, 196608, 1310720, 5242880, 12582912, 0 }
#define SQR_FFT_MODF_THRESHOLD          184
#define SQR_FFT_FULL_THRESHOLD         1472

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              10
#define MULLOW_MUL_THRESHOLD           2171

#define MULHIGH_BASECASE_THRESHOLD        8
#define MULHIGH_DC_THRESHOLD              8
#define MULHIGH_MUL_THRESHOLD          2171

#define MULMOD_2EXPM1_THRESHOLD          12

#define FAC_UI_THRESHOLD               8757
#define DC_DIV_QR_THRESHOLD              32
#define DC_DIVAPPR_Q_N_THRESHOLD         74
#define INV_DIV_QR_THRESHOLD           1099
#define INV_DIVAPPR_Q_N_THRESHOLD        74
#define DC_DIV_Q_THRESHOLD              108
#define INV_DIV_Q_THRESHOLD            1970
#define DC_DIVAPPR_Q_THRESHOLD           84
#define INV_DIVAPPR_Q_THRESHOLD        4420
#define DC_BDIV_QR_THRESHOLD             28
#define DC_BDIV_Q_THRESHOLD              34
/* Tuneup completed successfully, took 1592 seconds */
