# $Id: Makefile.inc 2026 2008-01-03 04:13:18Z peter $

TESTS += modules/arch/x86/tests/gas32/x86_gas32_test.sh

EXTRA_DIST += modules/arch/x86/tests/gas32/x86_gas32_test.sh
EXTRA_DIST += modules/arch/x86/tests/gas32/align32.asm
EXTRA_DIST += modules/arch/x86/tests/gas32/align32.hex
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-farithr.asm
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-farithr.hex
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movdq32.asm
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movdq32.hex
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movsd.asm
EXTRA_DIST += modules/arch/x86/tests/gas32/gas-movsd.hex
EXTRA_DIST += modules/arch/x86/tests/gas32/gas32-jmpcall.asm
EXTRA_DIST += modules/arch/x86/tests/gas32/gas32-jmpcall.hex

