#!/bin/bash

# run this script from the devel directory

# set version number
VERSION=3
VERSION_MINOR=0
VERSION_PATCHLEVEL=0

# these are the library soname numbers see
# http://sources.redhat.com/autobook/autobook/autobook_91.html
# or the start of Makefile.am to see what was done before

LIBGMP_LT_CURRENT=23
LIBGMP_LT_REVISION=3
LIBGMP_LT_AGE=0

LIBGMPXX_LT_CURRENT=12
LIBGMPXX_LT_REVISION=3
LIBGMPXX_LT_AGE=4

echo "Setting MPIR to"
echo "MPIR-$VERSION.$VERSION_MINOR.$VERSION_PATCHLEVEL"
echo "GMP-soname-$LIBGMP_LT_CURRENT.$LIBGMP_LT_REVISION.$LIBGMP_LT_AGE"
echo "GMPXX-soname-$LIBGMPXX_LT_CURRENT.$LIBGMPXX_LT_REVISION.$LIBGMPXX_LT_AGE"

###############################################################
##############################################################

VERSION_STR=$VERSION.$VERSION_MINOR.$VERSION_PATCHLEVEL
TMPFILE=$(mktemp mpir.XXXXXX)

#update gmp-h.in
cat ../gmp-h.in \
| sed s/"#define[[:space:]]\+__MPIR_VERSION[[:space:]]\+.*"/"#define __MPIR_VERSION "$VERSION/ \
| sed s/"#define[[:space:]]\+__MPIR_VERSION_MINOR[[:space:]]\+.*"/"#define __MPIR_VERSION_MINOR "$VERSION_MINOR/ \
| sed s/"#define[[:space:]]\+__MPIR_VERSION_PATCHLEVEL[[:space:]]\+.*"/"#define __MPIR_VERSION_PATCHLEVEL "$VERSION_PATCHLEVEL/ \
| sed s/"#define[[:space:]]\+_MSC_MPIR_VERSION[[:space:]]\+.*"/"#define _MSC_MPIR_VERSION "\"$VERSION_STR\"/ > $TMPFILE
mv $TMPFILE ../gmp-h.in

#update Makefile.am
cat ../Makefile.am \
| sed s/"LIBGMP_LT_CURRENT[[:space:]]*=[[:space:]]*.*"/"LIBGMP_LT_CURRENT = "$LIBGMP_LT_CURRENT/ \
| sed s/"LIBGMP_LT_REVISION[[:space:]]*=[[:space:]]*.*"/"LIBGMP_LT_REVISION = "$LIBGMP_LT_REVISION/ \
| sed s/"LIBGMP_LT_AGE[[:space:]]*=[[:space:]]*.*"/"LIBGMP_LT_AGE = "$LIBGMP_LT_AGE/ \
| sed s/"LIBGMPXX_LT_CURRENT[[:space:]]*=[[:space:]]*.*"/"LIBGMPXX_LT_CURRENT = "$LIBGMPXX_LT_CURRENT/ \
| sed s/"LIBGMPXX_LT_REVISION[[:space:]]*=[[:space:]]*.*"/"LIBGMPXX_LT_REVISION = "$LIBGMPXX_LT_REVISION/ \
| sed s/"LIBGMPXX_LT_AGE[[:space:]]*=[[:space:]]*.*"/"LIBGMPXX_LT_AGE = "$LIBGMPXX_LT_AGE/ > $TMPFILE
mv $TMPFILE ../Makefile.am

#update doc/version
echo -n "@set UPDATED " > ../doc/version.texi
date "+%d %B %Y" >> ../doc/version.texi
echo -n "@set UPDATED-MONTH " >> ../doc/version.texi
date "+%B %Y" >> ../doc/version.texi
echo "@set EDITION $VERSION_STR" >> ../doc/version.texi
echo "@set VERSION $VERSION_STR" >> ../doc/version.texi

#update makeinfo
cd ../doc
makeinfo mpir.texi
makeinfo version.texi
cd ..

autoreconf -fiv --no-recursive
rm -f $TMPFILE
cd devel
