/* Generated by tuneup.c, 2011-11-23, gcc 4.6 */

#define MUL_KARATSUBA_THRESHOLD          27
#define MUL_TOOM3_THRESHOLD             133
#define MUL_TOOM4_THRESHOLD             202
#define MUL_TOOM8H_THRESHOLD            309

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          64
#define SQR_TOOM3_THRESHOLD             159
#define SQR_TOOM4_THRESHOLD             336
#define SQR_TOOM8_THRESHOLD             342

#define POWM_THRESHOLD                  984

#define HGCD_THRESHOLD                   73
#define GCD_DC_THRESHOLD               1460
#define GCDEXT_DC_THRESHOLD            1138
#define JACOBI_BASE_METHOD                1

#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1  /* native */
#define DIVREM_2_THRESHOLD               21
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD               978
#define MOD_1_2_THRESHOLD               978
#define MOD_1_3_THRESHOLD               978
#define DIVREM_HENSEL_QR_1_THRESHOLD      2
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD      3
#define DIVREM_EUCLID_HENSEL_THRESHOLD     21

#define ROOTREM_THRESHOLD                11

#define GET_STR_DC_THRESHOLD             17
#define GET_STR_PRECOMPUTE_THRESHOLD     26
#define SET_STR_DC_THRESHOLD           9397
#define SET_STR_PRECOMPUTE_THRESHOLD  22420

#define MUL_FFT_FULL_THRESHOLD         1664

#define SQR_FFT_FULL_THRESHOLD         1920

#define MULLOW_BASECASE_THRESHOLD         7
#define MULLOW_DC_THRESHOLD              63
#define MULLOW_MUL_THRESHOLD           3539

#define MULHIGH_BASECASE_THRESHOLD        9
#define MULHIGH_DC_THRESHOLD             56
#define MULHIGH_MUL_THRESHOLD          3539

#define MULMOD_2EXPM1_THRESHOLD          18

#define FAC_UI_THRESHOLD               3500
#define DC_DIV_QR_THRESHOLD              40
#define DC_DIVAPPR_Q_N_THRESHOLD         59
#define INV_DIV_QR_THRESHOLD           2801
#define INV_DIVAPPR_Q_N_THRESHOLD        59
#define DC_DIV_Q_THRESHOLD              118
#define INV_DIV_Q_THRESHOLD            2350
#define DC_DIVAPPR_Q_THRESHOLD          110
#define INV_DIVAPPR_Q_THRESHOLD        2478
#define DC_BDIV_QR_THRESHOLD             60
#define DC_BDIV_Q_THRESHOLD              50
/* Tuneup completed successfully, took 800 seconds */

