/* Generated by tuneup.c, 2010-03-24, gcc 4.0 */

#define MUL_KARATSUBA_THRESHOLD          22
#define MUL_TOOM3_THRESHOLD              74
#define MUL_TOOM4_THRESHOLD             234
#define MUL_TOOM8H_THRESHOLD            238

#define SQR_BASECASE_THRESHOLD            0  /* always */
#define SQR_KARATSUBA_THRESHOLD          28
#define SQR_TOOM3_THRESHOLD              86
#define SQR_TOOM4_THRESHOLD             250
#define SQR_TOOM8_THRESHOLD             254

#define POWM_THRESHOLD                  984

#define GCD_ACCEL_THRESHOLD              62
#define GCDEXT_THRESHOLD                 27
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */
#define MOD_1_1_THRESHOLD                 8
#define MOD_1_2_THRESHOLD                 8
#define MOD_1_3_THRESHOLD                20
#define DIVREM_HENSEL_QR_1_THRESHOLD    996
#define RSH_DIVREM_HENSEL_QR_1_THRESHOLD    996
#define DIVREM_EUCLID_HENSEL_THRESHOLD     17

#define ROOTREM_THRESHOLD                 6

#define GET_STR_DC_THRESHOLD             10
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           7863
#define SET_STR_PRECOMPUTE_THRESHOLD  28988

#define MUL_FFT_TABLE  { 304, 736, 896, 3584, 14336, 24576, 163840, 655360, 2621440, 0 }
#define MUL_FFT_MODF_THRESHOLD          320
#define MUL_FFT_FULL_THRESHOLD         1152

#define SQR_FFT_TABLE  { 272, 736, 896, 3584, 10240, 40960, 163840, 655360, 2621440, 10485760, 0 }
#define SQR_FFT_MODF_THRESHOLD          232
#define SQR_FFT_FULL_THRESHOLD         1152

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              57
#define MULLOW_MUL_THRESHOLD           3609

#define MULHIGH_BASECASE_THRESHOLD        4
#define MULHIGH_DC_THRESHOLD             47
#define MULHIGH_MUL_THRESHOLD          2852

#define MULMOD_2EXPM1_THRESHOLD          20

#define FAC_UI_THRESHOLD              14512
#define DC_DIV_QR_THRESHOLD              68
#define DC_DIVAPPR_Q_N_THRESHOLD        273
#define INV_DIV_QR_THRESHOLD           3478
#define INV_DIVAPPR_Q_N_THRESHOLD       273
#define DC_DIV_Q_THRESHOLD              339
#define INV_DIV_Q_THRESHOLD            3410
#define DC_DIVAPPR_Q_THRESHOLD          309
#define INV_DIVAPPR_Q_THRESHOLD        3625
#define DC_BDIV_QR_THRESHOLD             67
#define DC_BDIV_Q_THRESHOLD             153
/* Tuneup completed successfully, took 1091 seconds */
