/* Generated by tuneup.c, 2009-02-27, gcc 4.2 */

#define MUL_KARATSUBA_THRESHOLD          17
#define MUL_TOOM3_THRESHOLD              98

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          26
#define SQR_TOOM3_THRESHOLD             105

#define MULLOW_BASECASE_THRESHOLD         5
#define MULLOW_DC_THRESHOLD              44
#define MULLOW_MUL_N_THRESHOLD          357

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 76
#define POWM_THRESHOLD                   85

#define GCD_ACCEL_THRESHOLD              25
#define GCDEXT_THRESHOLD                152
#define JACOBI_BASE_METHOD                1

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             12
#define GET_STR_PRECOMPUTE_THRESHOLD     14
#define SET_STR_THRESHOLD              7059

#define MUL_FFT_TABLE  { 464, 992, 2368, 3840, 9216, 28672, 81920, 327680, 1310720, 5242880, 0 }
#define MUL_FFT_MODF_THRESHOLD          480
#define MUL_FFT_THRESHOLD              2944

#define SQR_FFT_TABLE  { 560, 1184, 2368, 3840, 11264, 28672, 81920, 327680, 1310720, 5242880, 0 }
#define SQR_FFT_MODF_THRESHOLD          520
#define SQR_FFT_THRESHOLD              3456

/* Tuneup completed successfully, took 575 seconds */
